### ISSUE TITLE
Documentation on how to cleanly uninstall a Nautobot App

### ISSUE THREAD

**Issue by HanlinMiao** [nautobot/nautobot#4253] opened 2023-08-11 19:37 UTC
### Proposed Changes
There should be a dedicated section on how to uninstall a Nautobot App in the Nautobot App Developer Guide.

### Justification
This guide will provide assistance for App Developers to remove an unwanted Nautobot App with its migration history and data cleanly. As we are seeing an increasing number of issues caused by incorrect app uninstalls.

**Comment by bryanculver** [comment] 2023-08-11 21:39
Dupe of #3172?

**Closed** 2023-08-14 15:41 UTC
Labels: type: documentation, type: housekeeping
