### ISSUE TITLE
Postgres 10: 2.0 Migration error: `cannot ALTER TABLE "extras_jobresult" because it has pending trigger events`

### ISSUE THREAD

**Issue by joewesch** [nautobot/nautobot#4757] opened 2023-11-06 20:54 UTC
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.3
* Python version: 3.9
* Database platform, version: PostgreSQL v10.17
* Middleware(s):

### Steps to Reproduce
1. Have JobResult objects in Nautobot 1.6.2
2. Upgrade to Nautobot 2.0.3
3. Run `nautobot-server post_upgrade`

### Expected Behavior
Migrations to complete successfully

### Observed Behavior
```
Applying extras.0087_job__celery_task_fields__dryrun_support...Traceback (most recent call last):
  File "/opt/nautobot/lib64/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
    psycopg2.errors.ObjectInUse: cannot ALTER TABLE "extras_jobresult" because it has pending trigger events
 
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/opt/nautobot/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot/core/cli/__init__.py", line 54, in main
    run_app(
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot/core/runner/runner.py", line 297, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/nautobot/lib64/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot/core/management/commands/post_upgrade.py", line 100, in handle
    call_command(
  File "/opt/nautobot/lib64/python3.9/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/opt/nautobot/lib64/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/db/migrations/operations/fields.py", line 244, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/db/backends/base/schema.py", line 608, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "/opt/nautobot/lib64/python3.9/site-packages/django/db/backends/postgresql/schema.py", line 196, in _alter_field
    super()._alter_field(
  File "/opt/nautobot/lib64/python3.9/site-packages/django/db/backends/base/schema.py", line 785, in _alter_field
    self.execute(
  File "/opt/nautobot/lib64/python3.9/site-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/nautobot/lib64/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  django.db.utils.OperationalError: cannot ALTER TABLE "extras_jobresult" because it has pending trigger events
```

**Comment by glennmatthews** [comment] 2023-11-06 21:16
Current best guess is that this is due to having `JobResult` objects with a null `task_args` value (formerly `job_kwargs` in 1.x); this migration is trying to do:

```python
        migrations.AlterField(
            model_name="jobresult",
            name="task_args",
            field=models.JSONField(
                blank=True, default=list, encoder=nautobot.core.celery.encoders.NautobotKombuJSONEncoder
            ),
        ),
```

to make that field non-nullable, but without there being any data migration in place to fix existing nulls.

Again, at this time this is a *guess* - needs to be reproduced locally to confirm whether this is the issue.

**Comment by gsnider2195** [comment] 2023-11-06 23:31
@glennmatthews I'm unable to replicate using a `JobResult` with a null `job_kwargs`. It looks like it just picked the default value for the field. It has to be one of the other `AlterField` migrations but I don't see any reason why they would fail. 


```py
        # changes default from True to False
        migrations.AlterField(
            model_name="job",
            name="dryrun_default",
            field=models.BooleanField(default=False),
        ),
        # adds editable=False
        migrations.AlterField(
            model_name="job",
            name="read_only",
            field=models.BooleanField(default=False, editable=False),
        ),
        # adds editable=False
        # This field was added earlier in the migration, maybe this is why? Works for me though
        migrations.AlterField(
            model_name="job",
            name="supports_dryrun",
            field=models.BooleanField(default=False, editable=False),
        ),
```

**Comment by glennmatthews** [comment] 2023-11-07 15:51
Possibly related: https://code.djangoproject.com/ticket/25105 (fixed in Django 4.1).

Would be useful to confirm which version of PostgreSQL this is being observed with.

**Comment by gsnider2195** [comment] 2023-11-07 16:10
I was testing on mysql. Let me try postgres

**Comment by gsnider2195** [comment] 2023-11-07 17:30
It's not an issue in postgres 13 but the linked django issue was seeing the failure in postgres 9.

Test job result created with:

```py
>>> import uuid
>>> JobResult.objects.create(name="test null job_kwargs jr1", obj_type=ContentType.objects.get_for_model(Job), job_id=uuid.uuid4())
```

**Comment by joewesch** [comment] 2023-11-07 17:32
The PostgreSQL version in question is v10.17

**Comment by gsnider2195** [comment] 2023-11-07 17:35
Looks like it might be the same issue though (altering schema and updating data in one transaction):

```
root@1c1477f39481:/source# nautobot-server sqlmigrate extras 0087
BEGIN;
--
-- Rename field commit_default_override on job to dryrun_default_override
--
ALTER TABLE "extras_job" RENAME COLUMN "commit_default_override" TO "dryrun_default_override";
--
-- Rename field commit_default on job to dryrun_default
--
ALTER TABLE "extras_job" RENAME COLUMN "commit_default" TO "dryrun_default";
--
-- Alter field dryrun_default on job
--
--
-- Add field supports_dryrun to job
--
ALTER TABLE "extras_job" ADD COLUMN "supports_dryrun" boolean DEFAULT false NOT NULL;
ALTER TABLE "extras_job" ALTER COLUMN "supports_dryrun" DROP DEFAULT;
--
-- Remove field read_only_override from job
--
ALTER TABLE "extras_job" DROP COLUMN "read_only_override" CASCADE;
--
-- Remove field obj_type from jobresult
--
ALTER TABLE "extras_jobresult" DROP COLUMN "obj_type_id" CASCADE;
--
-- Remove field periodic_task_name from jobresult
--
ALTER TABLE "extras_jobresult" DROP COLUMN "periodic_task_name" CASCADE;
--
-- Remove field task_id from jobresult
--
ALTER TABLE "extras_jobresult" DROP COLUMN "task_id" CASCADE;
--
-- Add field celery_kwargs to jobresult
--
ALTER TABLE "extras_jobresult" ADD COLUMN "celery_kwargs" jsonb DEFAULT '{}' NOT NULL;
ALTER TABLE "extras_jobresult" ALTER COLUMN "celery_kwargs" DROP DEFAULT;
--
-- Add field celery_kwargs to scheduledjob
--
ALTER TABLE "extras_scheduledjob" ADD COLUMN "celery_kwargs" jsonb DEFAULT '{}' NOT NULL;
ALTER TABLE "extras_scheduledjob" ALTER COLUMN "celery_kwargs" DROP DEFAULT;
--
-- Alter field read_only on job
--
--
-- Alter field supports_dryrun on job
--
--
-- Alter field task_args on jobresult
--
ALTER TABLE "extras_jobresult" ALTER COLUMN "task_args" SET DEFAULT '[]';
UPDATE "extras_jobresult" SET "task_args" = '[]' WHERE "task_args" IS NULL;
ALTER TABLE "extras_jobresult" ALTER COLUMN "task_args" SET NOT NULL;
ALTER TABLE "extras_jobresult" ALTER COLUMN "task_args" DROP DEFAULT;
COMMIT;
```

**Comment by gsnider2195** [comment] 2023-11-07 18:57
I'm not able to replicate on postgres 10.17

**Comment by gsnider2195** [comment] 2023-11-08 15:53
I was finally able to replicate on postgresql 10.17 with this record:

```py
JobResult.objects.create(name="test jobresult null fields 2", obj_type=ContentType.objects.get_for_model(Job), user=User.objects.first(), status="completed", data=None, job_model=None, schedule=None, job_kwargs=None, job_id=uuid.uuid4())

```

For some reason it was only failing if `user_id` was not null.

Now to fix the original issue, setting the default value for `task_args` fixed the migration:

```sql
update extras_jobresult set task_args = '[]' WHERE task_args is NULL;
```

**Comment by joewesch** [comment] 2023-11-09 16:13
Confirmed that upgrading to PostgreSQL 13 succeeds as a workaround.

**Comment by lampwins** [comment] 2023-11-16 14:31
Do we care to do anything about this give version 10?

**Comment by glennmatthews** [comment] 2023-11-16 14:55
Honestly my preferred approach would be to revise our documentation to raise the floor of our minimum supported Postgres version (the docs still say we support Postgres 9.6 or later, but our CI uses Postgres 13 only). Perhaps we can make a formal declaration of such in 2.1?

**Comment by gsnider2195** [comment] 2023-11-16 14:56
I think our only possible fix would be to squash one of the data migrations to add the default value to the field before extras.0087.

**Comment by lampwins** [comment] 2023-11-17 19:44
We will drop support for postgres < 12 as these versions are no longer supported by postgres. This story will codify this into the documentation for 2.1.

**Comment by glennmatthews** [comment] 2023-12-05 18:10
Nautobot 2.1 has formally dropped support for postgres < 12, see #4910.

**Closed by glennmatthews** 2023-12-05 18:10 UTC
Labels: type: bug
