### ISSUE TITLE
Child Prefixes view shows Child Prefixes from another parent prefix

### ISSUE THREAD

**Issue by evdzande** [nautobot/nautobot#780] opened 2021-08-05 12:30 UTC
### Environment
* Python version:
* Nautobot version: v1.1.0

### Steps to Reproduce
Everything tested on the main.demo.nautobot.com site

1. create a prefix i.e. 192.168.0.0/16 and assign it to tenant Nautobot Airports
2. create a prefix i.e. 192.168.0.0/16 and do not assign it to a tenant
3. I added a description to the prefix with no tenant to determine which should not show a tenant in the Duplicate Prefixes table
4. create a couple of child prefixes (i.e. 192.168.0.0/24 - 192.168.5.0/24) under the 192.168.0.0/16 parent prefix assigned to tenant Nautobot Airports

### Expected Behavior
The child prefixes should only show under the 192.168.0.0/16 parent prefix assigned to tenant Nautobot Airports

### Observed Behavior
The child prefixes are shown under both 192.168.0.0/16 prefixes.
Also when you go into a child prefix, i.e. 192.168.0.0/24 you see both prefixes in the Parent Prefixes table both with the Tenant column filled where only one should be. Same issue as #779

**Comment by glennmatthews** [comment] 2021-08-11 20:20
Thanks for the report! For what it's worth, the same behavior is seen in NetBox 2.11.10. I'm not entirely certain at this time that this behavior is a bug versus the feature working as intended, as it seems like a reasonable use case to have a parent Prefix with no Tenant as the parent of variou child Prefixes each of which are assigned to different Tenants.

**Comment by evdzande** [comment] 2021-08-11 21:17
OK, that sounds as reasonable indeed, a parent Prefix with no Tenant as parent of various child Prefixes which are assigned to different Tenants. I did some more tests. The view is not intuitive in my opnion. See attached screenshot. With this view it seems the several child Prefixes belong to the 192.168.0.0/16 assigned to no Tenant but are assigned to tenant Nautobot Airports.
![image](https://user-images.githubusercontent.com/82216020/129101698-51081bf1-a54a-454b-8141-3287dd0dfafc.png)

Also if you would now like to create a child Prefix 192.168.0.0/24 under the no Tenant 192.168.0.0/16. So you cannot click it to easily create it. Also if you click the Add Child button it does not come with the first free prefix within no Tenant 192.168.0.0/16 but with the first free prefix from tenant Nautobot Airports.

Then when you go to the 192.168.0.0/16 assigned to tenant Nautobot Airports you also see the 192.168.0.0/24 Child Prefix from the no Tenant which is not correct offcourse.
![image](https://user-images.githubusercontent.com/82216020/129103573-3b56c3a5-3cdf-4df2-9fe1-816bfd22a30b.png)

Also when you create for example a 192.168.6.0/24 under no Tenant. It is not available as free Child Prefix any more under tenant Nautobot Airport.
![image](https://user-images.githubusercontent.com/82216020/129104029-f6def106-9d1f-4b31-99f9-9d2e05132733.png)

Also added 192.168.7.0/24 but now to Tenant Network to Code. Lets take a look under the 192.168.0.0/16 assigned to tenant Nautobot Airports:
![image](https://user-images.githubusercontent.com/82216020/129104422-732c3646-3a09-45a4-81d7-c068f90ce6a5.png)

So I think there is a bug with this ;-)

**Comment by jathanism** [comment] 2021-08-12 20:08
Okay, grab a coffee and have a seat because this issue is a doozy!

This issue is a blend of "working as intended" and “huh?”, since the intent of how it is working is not consistent, so it is negatively affecting the user experience at best. 

As I see it allowing duplicate prefixes is really the core issue here. In my very strong opinion, there should be a uniqueness constraint on `(network, prefix_length, tenant)` for starters. VRFs are also an important part of the equation here, because they are the only extra filtering criteria that is being considered within database queries and therefore default ordering of prefixes.

I cannot think of a single real-world use case where you'd have the same prefix in use multiple times in a single "namespace", but I am but one person. We'll need to clarify that in detail.

## What is happening?

The mapping of the children that get correlated to a `Prefix` to which tenant when rendered in a table view is completely arbitrary based on existing order. In actuality, tenancy is not considered whatsoever.

So for example if you create Prefix 1 and Prefix 2 (using the same prefixes e.g. `192.168.0.0/16`), and assign Prefix 1 a tenant and Prefix 2 no tenant, since they both have the same `network` and `prefix_length`, the ordering becomes non-deterministic and I can only assume it falls back to UUID (which we know to be random).

## Data model assessment

There are not **any** uniqueness constraints at all on `Prefix` objects. So if we were to try to solve this without changing the data model, at a minimum it would result in greatly complicated view code to make render-time decisions to group prefixes by tenants "somehow". But how do we decide? The relationship of child prefixes to the tenant of the parent is only inherited if the prefix is added from that exact instance that has the tenant as illustrated in the initial example above.

But then there are all the edge cases we need to account for such as "what if parent prefix is in tenant A and child is in tenant B, but I want to allocate a duplicate prefix for another tenant". I can't even imagine trying to manage the data that way and I would welcome anyone to provide input on tangible real-world use-cases that would require duplicate prefixes in the same namespace? To me it seems like an overwhelming matrix of possibilities. Would it not be more desirable to have _unique instances of each prefix for each tenant_? This is a gap we need to cover.

Another core issue with the data model is there is no actual schema-enforced relationship between any two Prefixes. This correlation is done using an [annotation query](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#annotate) at call time when rendering `Prefix` list views to add a `parents` and `children`  fields to the result set using a specialized queryset method [`Prefix.objects.annotate_tree()`](https://github.com/nautobot/nautobot/blob/develop/nautobot/ipam/querysets.py#L243-L306). VRF is considered here, tenancy is not. 

Outside of using `Prefix.objects.annotate_tree()`, there’s no other way from a database query perspective to reliably introspect the tree hierarchy for Prefixes outside of the list views. With a non-obvious way to access critical parts of the data model, and therefore if we wanted to display the same values in the REST API or GraphQL, we’d have to solve for this presentation problem separately. This has the undesirable effect in every bit of view code being a one-off, and the one bit of code that is using this pattern to present a confusing user experience.

## Proof

### Setup

- Two Prefixes each with `192.168.0.0/16`
- one with no tenant and description `"no tenant"`
- one with tenant `Nautobot Airports`
- 5x children (`192.168.[0-5].0/24`) added to the `"no tenant"`  prefix

Children show as nested under the `Nautobot Airports` prefix:

![Cursor_and_Prefixes_-_Nautobot](https://user-images.githubusercontent.com/138052/129260594-84427826-6555-42b2-b977-ed3503900123.png)

### Update prefixes
- Update `"no tenant"` Prefix with description `"TENANT (Before: no tenant)"` and adding tenant `Nautobot Airports`
- Update other prefix with description `"NO TENANT (Before: tenant Nautobot Airports)"` and remove tenant

Children still show as nested under the same prefix as before, confirming that tenancy is not considered at all for list views:

![Prefixes_-_Nautobot](https://user-images.githubusercontent.com/138052/129260632-d792c61b-2afe-4d91-9d72-fef5ceba27d9.png)

## Questions
- @evdzande Do you have a real world use-case that requires duplicate prefixes in same Global VRF across multiple tenants? If so, can you please help elaborate on precise details on what your desired behaviors and outcomes would be (outside of what you already explained here)?

We have several other questions to answer to move forward:

1. Is this desired behavior?
2. Is it merely a presentation problem, or is this a data model problem?
3. If it's a presentation problem, do we want to fix it with some updated template code?
4. If it's a data model problem, what would the desired constraints actually be? 

## My personal answers
1. Yes.
2. Both, but predominantly data model.
3. No.
4. Many and varied. Deeper analysis is required on what the path forward should be with specific emphasis on real-world use cases on duplicate prefixes and allocation child prefixes in the context of multi-tenant environments possibly also leveraging VRFs. Each permutation must also be considered (with global VRF and no tenants, with distinct VRFs and no tenants, with global VRF and tenants, with distinct VRFs and tenants). 

## Conclusion

We have a lot to think about and a lot of questions to answer. No matter how you slice it, we're in for a complicated solution. Especially if we want to clarify how these objects are all expected to interact, and we need to be crystal clear about what, exactly, each outcome should be and assert that with integration testing.

**Comment by evdzande** [comment] 2021-08-12 21:19
Thanks for further investigating.

How I discovered this:
We started documenting our core network within Nautobot with several Tenant specific VRFs, Tenant specific public IPv4 prefixes/IP addresses, etc. Also prefixes/IP addresses which are used  by our core network for management etc.

All prefixes/IP addresses needed by our core network are not assigned to a tenant as they are needed for the functioning of our core network not specific for any Tenant. The Tenant specific VRFs do have overlapping prefixes and IP addresses. But with this there are no issues because if you assign the same prefixes to different VRFs you only see the prefixes for the VRF you are looking at.

Now we are at the point we would like to add the LAN prefixes for several Tenants. Tenants do have overlapping and/or same Prefixes. But if you add 192.168.0.0/16 to Tenant X, it shows as not available at Tenant Y (which maybe is not the case in reality) as I explained earlier.

To answer you question: I also cannot think of a single real-world use case where you'd have the same prefix in use multiple times in a single "namespace".

In my opinion this should work the same as with the VRFs. I do not want to see prefixes/IPs from other Tenants when viewing Tenant X because it has nothing to do with this Tenant. Also if I Iook at the view rendering of VRFs it seems the several prefixes and child prefixes are rendered correctly in the correct order under the correct VRF.

Hopefully I have cleared things up this way.

**Comment by bryanculver** [comment] 2023-02-09 21:54
@nautobot/core I believe this will be resolved when we implement #2915?

**Comment by gsnider2195** [comment] 2023-02-10 14:42
> @nautobot/core I believe this will be resolved when we implement #2915?

Yes, the parent relationship will be used after #2915 is implemented and we can rip out the inconsistent parent/child code that @jathanism talks about above

**Comment by bryanculver** [comment] 2023-02-14 20:16
Will be implemented by #2915

**Closed by bryanculver** 2023-02-14 20:16 UTC
Labels: type: feature
