### ISSUE TITLE
Deleting Git Repository object in Nautobot GUI

### ISSUE THREAD

**Issue by the-bhattman** [nautobot/nautobot#5088] opened 2024-01-11 18:11 UTC
Problem:  When deleting the git repo object in Nautobot, it produced a error stating it had a 403 error, while attempting delete the git Report object.

### Environment
* Nautobot version (Docker tag too if applicable):2.0.5
* Python version:  3.10.8
* Database platform, version: Postgres, 14.9
* Middleware(s): None

### Steps to Reproduce
1. Create a Secret and group secret
2. Create a GIT Repository
3. Do the a successful dry run
4. Delete the Git Repot

  The GIT Repo was successfully deleted

    Error was produced in the GUI
    <class 'git.exc.GitCommandError'>
    
    Cmd('git') failed due to: exit code(128)
      cmdline: git fetch -v -- origin
      stderr: 'fatal: unable to access 'https://github.com/############/projects/': The requested URL returned error: 403'
    
    Python version: 3.10.8
    Nautobot version: 2.0.5

I logged into Nautobot via SSH and performed delete the directory under /opt/nautobot/git via rm -r <object>.  Then I went back into the GUI and deleted the object name successfully

**Comment by timizuoebideri1** [comment] 2024-06-27 05:26
> I ran into the same issue as well.
> 
> Problem: Cannot delete failed sync git repo object. Especially when you don't specify `GIT_SSL_NO_VERIFY` to a private gitlab instance
> 
> # Environment
> * Deployed to Kubernetes using helm chart v2.0.5
> * Nautobot docker version `:stable` (v2.1.4)
> * External postgresql database
> 
> # Steps to Reproduce
> 1. Do not specify the `GIT_SSL_NO_VERIFY` env var
> 2. Do not create a secret
> 3. Add a private git repo and do dry-run - This should fail as expected
> 4. Try to delete the git object and it fails with following output
> 
> # Output
> ```
> <class 'git.exc.GitCommandError'>
> 
> Cmd('git') failed due to: exit code(128)
>   cmdline: git clone -v -- https://gitlab.<redacted>/it/automation/nautobt-libs.git /opt/nautobot/git/nautobot_libs
>   stderr: 'Cloning into '/opt/nautobot/git/nautobot_libs'...
> fatal: could not read Username for 'https://gitlab.<redacted>': terminal prompts disabled
> '
> 
> Python version: 3.11.8
> Nautobot version: 2.1.4
> ```

I'm not able to replicate on v2.1.4. @nodespar

**Comment by glennmatthews** [comment] 2024-06-28 15:03
Closing for now as we cannot reproduce the issue locally. If you're still encountering this with latest Nautobot, please let us know and/or re-open this issue.

**Closed by glennmatthews** 2024-06-28 15:03 UTC
Labels: type: bug, good first issue, question
