### ISSUE TITLE
Add Non Racked Spaces

### ISSUE THREAD

**Issue by cmacnevin** [nautobot/nautobot#613] opened 2021-06-23 21:08 UTC
### Proposed Functionality
Create new organization objects:
    (1)'Rooms', equivalent in hierarchy to Rack Groups
    (2)'Spaces,' equivalent to Racks, without rack units specified
(1) may refer to a storage room, loading dock, cubicle, etc
(2) may refer to a shelf, bin, bench, desk, etc

### Use Case
All data center owning companies have store rooms and cubicles, and many have labs with benches and loading docks. For companies using Nautobot for asset management, that can represent millions of dollars of assets which can't easily be tracked in Nautobot/Netbox, and necessitates augmenting the system with spreadsheets, and in many cases, other asset management tools like Service NOW.

Creating non racked spaces can enable end to end asset management.

Additional use cases include a place to hook in RFID tracking systems and similar.

### Database Changes
TBD

### External Dependencies
None

**Comment by ebusto** [comment] 2021-06-23 22:23
This sounds like a great idea.

**Comment by glennmatthews** [comment] 2021-06-24 12:38
Thank you for the feature request! To my mind this aligns closely with some of the ideas we're also considering in #230.

**Comment by glennmatthews** [comment] 2021-08-24 19:57
I'm going to mark this as a duplicate of #774 as it falls within the scope of that broader epic. We'll make sure this gets addressed as a part of that. Thank you!

**Closed by glennmatthews** 2021-08-24 19:57 UTC
Labels: workflow: under review, type: feature
