### ISSUE TITLE
Circuits: can't swap terminations

### ISSUE THREAD

**Issue by david-kn** [nautobot/nautobot#2405] opened 2022-09-12 09:15 UTC
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.1
* Python: 3.7.13
(demo instance)

### Steps to Reproduce
1. Open a circuit with set terminations A and Z (e.g. https://demo.nautobot.com/circuits/circuits/9fff50ee-1bed-466c-8ec7-22a215e4d907?tab=main)
2. Click `Swap` and `Confirm` to swap terminations.

### Expected Behavior
Terminations should be swapped.

### Observed Behavior
Internal exception `django.core.exceptions.FieldDoesNotExist` appears (see image)

![image](https://user-images.githubusercontent.com/14314517/189616855-b424b66e-0a01-446b-bafb-aecc5d6bb839.png)

**Comment by smk4664** [comment] 2022-09-12 12:40
This is the same issue as #2326

**Comment by bryanculver** [comment] 2022-09-12 13:14
Duplicate of #2326

**Closed by bryanculver** 2022-09-12 13:14 UTC

**Comment by david-kn** [comment] 2022-09-13 11:06
Sorry, I missed that it's been already reported.

Thanks
