### ISSUE TITLE
Custom Fields API endpoint - missing grouping and advanced_ui

### ISSUE THREAD

**Issue by EdificomSA** [nautobot/nautobot#4384] opened 2023-09-05 13:21 UTC
### Environment
* Nautobot version : 1.5.24
* Python version: 3.10
* Database platform, version: postgres 14
* Middleware(s): 

### Steps to Reproduce
1. Get request on `/extras/custom-fields/` or `/extras/custom-fields/{id}` or read API doc `/api/docs/#/extras/extras_custom_fields_list`
2. There are no filter parameter for grouping nor advanced_ui, nor the field in the response
3. Same for the POST endpoint, so unable to set advanced_ui bool nor grouping from API

### Expected Behavior
Having "advanced_ui" and "group" fields available for all API REST methods

### Observed Behavior
These fields are not there.

Linked to these PR implementing grouping and advanced_ui bool
#1392
#2317

**Comment by gsnider2195** [comment] 2023-09-05 18:37
Only affects Nautobot <2.0.0

**Comment by bryanculver** [comment] 2023-09-05 18:52
Dupe of #3265

**Closed by bryanculver** 2023-09-05 18:52 UTC
Labels: type: bug
