### ISSUE TITLE
Job Soft Time Limit not being respected after upgrading from 2.2.0 to 2.2.5

### ISSUE THREAD

**Issue by gneville-ot** [nautobot/nautobot#5785] opened 2024-06-05 10:18 UTC
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.5
* Python version: 3.11
* Database platform, version: PG 15
* Middleware(s): None

### Steps to Reproduce
1. Have a job imported via a git repo that has a soft time limit set to, say, 15 mins and within the code let it sleep 10 mins before it completes
2. Try and run the job and see that the soft time limit isn't respected and the job is stopped after 5 minutes (the default)

### Expected Behavior
The Soft Time Limit is respected and the job completes after 10 mins

### Observed Behavior
The job is killed due to the Soft Time Limit not being respected and is killed after 5 minutes

```
  File "/usr/local/lib/python3.11/site-packages/billiard/pool.py", line 228, in soft_timeout_sighandler
    raise SoftTimeLimitExceeded()
billiard.exceptions.SoftTimeLimitExceeded: SoftTimeLimitExceeded()
```

**Comment by HanlinMiao** [comment] 2024-06-12 15:05
Investigate the HardTimeLimit as well as SoftTimeLimit.

**Comment by timizuoebideri1** [comment] 2024-06-18 08:23
## Steps taken to reproduce error:

- Installed Nautobot v2.2.0
- Upgrade to Nautobot v2.2.5
- Added Git Repo, then Sync Repo - (`soft_time_limit=15*60` is the soft time limit of the job)
- Enabled the newly added Job then Run the Job
- Job runs for 10 mins [Job seems to work fine]

## Another Trial 
- Gave another trial but first removed the `soft_time_limit in the job
- Now Job fails at 5 mins cause nautobot used the default `soft_time_limit`.


@gneville-ot I could not reproduce this bug, its either you didn't set the `soft_time_limit` correctly, or its related to #5782.

**Comment by gneville-ot** [comment] 2024-06-18 14:08
Thanks @timizuoebideri1 , I think this is directly related to [#5782](https://github.com/nautobot/nautobot/issues/5782).

**Comment by Keegan-Sequeira** [comment] 2024-06-20 23:32
I am also facing this same issue, however, the job is not being imported from a git repo, and is created from a plugin. 

I see this warning in the logs `Soft time limit (300s) exceeded for nautobot.extras.jobs.run_job`

However, the job's soft time limit. Can see it has been set through the job, and shows in nautobot:
![image](https://github.com/nautobot/nautobot/assets/101374214/5bc8774e-c3db-4b5f-9521-319bfe328c67)

**Comment by glennmatthews** [comment] 2024-06-25 17:33
After fixing #5782 we are so far unable to reproduce this issue locally either with Git or App Jobs. Closing this for now, but please let us know if you still encounter this issue after updating to 2.2.6 or later and we can reopen it if so.

**Comment by glennmatthews** [comment] 2024-07-02 14:16
We have an additional report that this may be *specific* to scheduled jobs rather than ad-hoc runs of jobs. Reopening to test this possibility.

**Comment by emdeefive** [comment] 2024-07-02 15:32
Hi Team, I'm able to personally reproduce this issue on 2.2.3.  I also work with a team who reported this issue to me on 2.1.2 and 2.2.5.  This issue appears to only affect scheduled jobs.  To reproduce, you can just create a job that sleeps for 7 minutes.  Set the hard and soft time limits to 6 minutes in the job code meta section and/or in the edit job section of the UI (override).  Run the job ad-hoc and you'll see that the job ends at 6 minutes for "TimeLimitExceeded."  If you schedule the job it will fail at 5 minutes for "SoftTimeLimitExceeded."  I'm including a screenshot of a scheduled job result that shows:

1 - The time limits are set to 6 minutes in the meta section, you can see the warning in the logs stating that they are the same
2 - The job goes to sleep for 7 minutes
3 - The job ends at 5 minutes for SoftTimeLimitExceeded

When running this same job ad-hoc it fails at 6 minutes as expected.

As a work around, setting hard and soft time limits in nautobot_config.py (CELERY_TASK_SOFT_TIME_LIMIT and CELERY_TASK_HARD_TIME_LIMIT) the scheduled jobs complete as expected.  This is undesirable though because those are global settings.

![image](https://github.com/nautobot/nautobot/assets/52513531/fb593083-7e68-48de-afcb-4efdcdc2104e)

**Closed** 2024-07-23 06:34 UTC
Labels: type: bug, triage
