### ISSUE TITLE
Allow user to apply a default filter to the list view

### ISSUE THREAD

**Issue by joewesch** [nautobot/nautobot#3530] opened 2023-04-03 21:23 UTC
### As ...

Ozzie - Operator

### I want ...

To be able to apply a default filter to a model's list view.

### So that ...

So that I can hide certain items from view by default, but still have the ability to view them explicitly.

### I know this is done when...

- I can hide all Devices in the list view that are of a status of Decommissioned
- I can hide all Locations that have a specific parent Location

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [X] Circuits
- [X] DCIM
- [X] IPAM
- [X] Misc (including Data Sources)
- [X] Organization
- [X] Plugins (and other Extensibility)
- [X] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

I don't think so.

### External Dependencies

I don't think so.

**Comment by joewesch** [comment] 2023-04-03 21:23
Similar to #1500

**Comment by gsnider2195** [comment] 2024-05-13 15:48
Is this now a duplicate of #5471?

**Comment by lampwins** [comment] 2024-06-28 18:03
This is now Saved Views, available in next.

**Closed by lampwins** 2024-06-28 18:03 UTC
Labels: type: feature
