### ISSUE TITLE
Grouping variable stays empty when creating custom-fields through the API

### ISSUE THREAD

**Issue by MarcHoog** [nautobot/nautobot#4278] opened 2023-08-17 07:39 UTC
### Environment
* Nautobot version: networktocode/nautobot:1.5.24-py3.10
* Python version: 3.10
* Database platform, version: postgres:13
* Middleware(s):

### Steps to Reproduce
1.  Creating a new custom-field over the api
```
curl --location 'http://localhost:8080/api/extras/custom-fields/' \
--header 'Content-Type: application/json' \
--data '{
    "label": "test0",
    "slug": "test0",
    "name": "test0",
    "grouping": "testing",
    "type": "text",
    "content_types": [
        "dcim.device"
    ],
    "required": false,
    "filter_logic": "loose",
    "default": null
}
```
2.  ![image](https://github.com/nautobot/nautobot/assets/58691229/ad784b69-fb32-4e60-a2c1-a3d51d0fcf58)

### What did you expect to happen
Expected a custom variable to be created, with the grouping variable filled in

### What happened instead?
A custom variable was created without the grouping variable empty even through it was passed in the request

**Comment by bryanculver** [comment] 2023-09-05 18:53
Dupe of #3265

**Closed by bryanculver** 2023-09-05 18:53 UTC
Labels: type: bug
