### ISSUE TITLE
Git Datasource - Add functionaity to read GraphQL queries

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#1890] opened 2022-06-15 12:23 UTC
### As ...

Austin - Network Automation Engineer

### I want ...

to consistently update stored GraphQL queries on different Servers.

### So that ...

my automation tools (Ansible, Nornir) will get latest data structure when querying different Nautobot installations.

### I know this is done when...

- I create the subdirectory "graphql" and store the query as a .json or .yml file

   ```
  # graphql/get-interface-data.yml

   _metadata:
       name: get-interface-data
       weight: 1400
       description: Get interface specific data
       is_active: true
   query_variables:
       device_name: "[String]"
       interface_name: "[String]"
  query: |
        query ($device_name: [String], $interface_name: [String]) {
          devices(name__ie: $device_name) {
            name
            interfaces(name__ie: $interface_name) {
              name
              description
              label
              cf_interface_config_template
              cf_interface_custom_data
              cf_interface_dhcp_trust
              cf_interface_multi_auth
              cf_interface_static_sgt
              tags {
                name
              }
              mode
              lag {
                name
              }
              type
              untagged_vlan {
                vid
                name
                id
              }
              id
              device {
                virtual_chassis {
                  master {
                    name
                    id
                    primary_ip4 {
                      host
                      prefix_length
                      address
                      id
                    }
                  }
                }
                device_type {
                  model
                  id
                }
                config_context
              }
            }
            virtual_chassis {
              id
              master {
                id
                name
              }
            }
          }
        }
   ```

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by glennmatthews** [comment] 2022-06-15 12:37
Thanks for the request! Is this a duplicate of #1247?

**Comment by jifox** [comment] 2022-06-15 17:02
Yes, it is a duplicate. I haven't found it by searching for datasource

**Closed** 2022-06-15 17:15 UTC
Labels: closed: duplicate
