### ISSUE TITLE
Dark Mode for UI

### ISSUE THREAD

**Issue by mkrieger95** [nautobot/nautobot#1781] opened 2022-05-17 17:04 UTC
### As ...

Nelly - Network Engineer

### I want ...

To be able to switch the UI from "light mode" to "dark mode" from a toggle switch in settings or other designated area.

### So that ...

I am able to adjust the UI in a way that makes it easiest for me to view it. 

(ex: Working very early in AM, bright white screen can be very overpowering)

### I know this is done when...

I am able to use the user dropdown menu or click a button present across all screens to switch the UI from a light mode to dark mode as I please. 

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

I do not think this would require any DB changes -?

**Comment by smk4664** [comment] 2022-05-17 18:43
This is a duplicate of #729, and there is an open PR #1554 that will be addressing this Feature Request.

**Comment by bryanculver** [comment] 2022-05-17 19:06
Closed as duplicate of https://github.com/nautobot/nautobot/issues/729

**Closed by bryanculver** 2022-05-17 19:06 UTC
Labels: type: feature
