### ISSUE TITLE
Custom links create overflow issues on model views with lots of tabs when resizing the browser window

### ISSUE THREAD

**Issue by cmsirbu** [nautobot/nautobot#5432] opened 2024-03-15 19:00 UTC
### Environment
* Nautobot version (Docker tag too if applicable): 2.1.7 https://demo.nautobot.com/
* Browsers: Chrome and Firefox on Ubuntu behave the same (latest versions)

### Steps to Reproduce
1. Create a new Custom Link button for Device objects
2. Navigate to a Device page and resize the browser window

### Expected Behavior

Tab buttons next to the custom link button would overflow from 1 row to the next row only.

### Observed Behavior

[custom-link-overflow.webm](https://github.com/nautobot/nautobot/assets/9288571/346dd4cd-b2a2-4698-b2d1-af5eb7c31d48)

**Comment by glennmatthews** [comment] 2024-03-18 13:15
Duplicate of #5184. The video is helpful though, I'll copy it to that issue.

**Closed by glennmatthews** 2024-03-18 13:15 UTC
Labels: type: bug, triage
