### ISSUE TITLE
Have device custom fields only on specific types/roles/platforms

### ISSUE THREAD

**Issue by jnmms** [nautobot/nautobot#2930] opened 2022-12-01 09:24 UTC
### As ...

Austin - Network Automation Engineer

### I want ...

When using custom fields it would be awesome to being able to only add specific fields to specific devices within a defines role/type or platform.
That would really clean up the device view, and limit the number of empty fields on a device.

Example:
On a CheckPoint VSX machine a VSID could be an interesting field, but this is useless on a Cisco ASA
On a physical device some specific hardware config could be interesting, where on a virtual  device this info is uninteresting.

Caveat:
If a device changes type, role or platform - some default behaviour needs to be decided, is it then ok that the field contents is just removed/deleted

### So that ...

It will clean up the device view, and will have more specific fields for each device

### I know this is done when...

When I can add a custom field to a device type, role or platform that will stick to all devices with that role, type or platform.

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [X] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

My guess is that this would maybe require some new relationship tables between custom fields and devices over types, roles and platforms, but I do not work directly with the nautobot database.

**Comment by glennmatthews** [comment] 2022-12-01 14:10
Thanks for the request! I think this is a duplicate of #889, but you raise some interesting points about data updates, when an object changes in such a way as to change which custom fields apply to it, that I don't think were well-documented as concerns before.

**Comment by jnmms** [comment] 2022-12-02 05:39
I see in that ticket that basically it's a similar request, but his environment an mine is quite different, as he is using it for customer devices across different of his clients, whereas I am not needing that feature as much as the fields to be unique across specific types/roles and/or platforms.
But it seems like the structure of this feature request is very similar, and the 2 requests could easily be merged together into one future release, should they be accepted.

Thanks for replying

**Comment by bryanculver** [comment] 2022-12-02 14:01
@jnmms I have closed this as a duplicate but I have included it as an additional use case for #889.

**Closed by bryanculver** 2022-12-02 14:01 UTC
Labels: type: feature
