### ISSUE TITLE
Job Submission - Rerun and details

### ISSUE THREAD

**Issue by mattmiller87** [nautobot/nautobot#2623] opened 2022-10-17 20:35 UTC
### As ...

Ozzie - Operator

### I want ...

To see the details used to run a job, to be able to re-run the job and edit the details. It would be useful to see the filters used to submit the job

### So that ...

Jobs are a bit abstract and having more information for how they were historically ran by providing the filters would enable a better understanding of the jobs.  Furthermore, being able to re-run the job and submit or re-run the job and modify a value before submitting would be useful.

### I know this is done when...

- I can view the information used to create the job.
- I can re-run the job without it automatically starting
- I can re-run the job and tweak 1 or more items before starting the job

### Optional - Feature groups this request pertains to.

- [X] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [X] Other (not directly a platform feature)

**Comment by bryanculver** [comment] 2023-05-03 18:03
Closing as dupe of https://github.com/nautobot/nautobot/issues/1875

**Closed by bryanculver** 2023-05-03 18:03 UTC
Labels: type: feature
