### ISSUE TITLE
Automatic keyboard focus on buttons and forms

### ISSUE THREAD

**Issue by david-kn** [nautobot/nautobot#1993] opened 2022-07-01 10:44 UTC
### As ...

Dan - Data Owner

### I want ...

to have main buttons focused for keyboard automatically. 

e.g
1) Enter for confirming operations - e.g Delete VLAN - _Confirm_ (see image)
![image](https://user-images.githubusercontent.com/14314517/176872780-bbe39321-112d-4bcd-9f75-1b4d77cf9f13.png)

2) Switch between fields by Tab (e.g. in Create, Edit object windows).

### So that ...

a user can faster confirm operation and navigate within UI without a necessity to always use mouse.

### I know this is done when...

- I can confirm Delete dialog by Enter
- I can use Tab key to switch between main fields / buttons in forms 

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by bryanculver** [comment] 2023-08-10 21:48
Similar #1537

**Comment by glennmatthews** [comment] 2024-09-11 19:02
Duplicate of #1537.

**Closed by glennmatthews** 2024-09-11 19:02 UTC
Labels: type: feature
