### ISSUE TITLE
Display Custom-Field having attributes "required" and "default"

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#532] opened 2021-06-04 09:30 UTC
### Environment
* Python version: 3.6.8
* Nautobot version: 185c5691baf4 (v1.0.2)

If a new custom-field that is required and has a default value defined is added, the UI don't show the correcect value.

For e.g.  Custom Field "interface_config_template" that defines a custom field for dcim | interface

![image](https://user-images.githubusercontent.com/8406301/120778100-43b07900-c526-11eb-8b01-5f949765ac88.png)

When opening an existing Interface in UI, the value of the custom field will be shown as empty instead of displaying the default. When "Edit" is clicked, the default vlaue is correctly inserted in the custom_field and will be shown in Intefaces correctly

**Incorrect example - should reflect the default value if 'Not defined'**

![image](https://user-images.githubusercontent.com/8406301/120779328-3f389000-c527-11eb-828c-d80e91013aba.png)

**Same record after clicking the Buttons "Edit" /  "Update"**
![image](https://user-images.githubusercontent.com/8406301/120779790-b79f5100-c527-11eb-9271-f4ea4b3d9cb3.png)

### Steps to Reproduce
1. Add Custom Field with attribute Required and having default value defined
2. Open existing entry

### Expected Behavior

Nautobot should display the **default value** for required fields with default defined instead of '**Not defined**

### Observed Behavior

Value displyaed is "Not defined"

**Comment by jathanism** [comment] 2021-06-04 16:04
In the first example, I confirmed that this is a weird side effect of combining `required` with `default`. This is unexpected behavior. I would expect personally that when I go to edit or create an object w/ a required field that has a default value, that the value should automatically be populated in the form.

> Same record after clicking the Buttons "Edit" / "Update"

Where you've clicked edit/update, did you manually fill out this field w/ a value? Just want to confirm that behavior.

**Comment by jifox** [comment] 2021-06-06 04:04
Hi, I've also checked again the the selection field is populate with the default value on just pressing Edit/Update. It is definitly shown. But I forgot to mention, thatI have configured "exact" instead of "loose" for that field too.

**Comment by smk4664** [comment] 2021-06-09 03:03
I did a little digging into this, when creating a new custom field, it seems that the job `provision_field` that gets executed by the signal `handle_cf_removed_obj_types` is only executed when the custom field has a model added or removed, not during custom field creation.

**Comment by jifox** [comment] 2021-06-18 04:03
It turns out, that only the Selection fields will be automatically set when pressing Edit

**Comment by FragmentedPacket** [comment] 2021-07-12 04:09
@smk4664 You're correct since it's using the `.through`. I can implement a fix for this which I believe should be pretty simple, but wondering if we're wanting to behavior to update all relevant content types on creation of the custom field?

**Comment by jathanism** [comment] 2021-12-21 20:55
@jifox We're doing some backlog grooming and going to try to tackle this and it appears that this is no longer an issue as of Nautobot v1.2.x. The Custom Field forms have been moved into the UI and this now works as intended.

Steps to reproduce:

- Create a new Custom Field with "required" checked and a "default" value defined, mapping it to Device
- Go to a Device, observe that the field value is already populated with the default
- Profit!

**Closed** 2022-03-22 19:33 UTC
Labels: type: bug, status: accepted
