### ISSUE TITLE
Enable Jinja for "Source filter" and "Destination filter" to filter related items based on the source object data

### ISSUE THREAD

**Issue by jifoxpa** [nautobot/nautobot#5057] opened 2024-01-06 06:54 UTC
### As ...

Nelly - Network Engineer

### I want ...

filter related items based on the source object data.

This functionality would allow for actions like adding VLAN-Groups to a Device while restricting the selectable VLAN-Groups based on the device's location. To achieve this, Jinja should be enabled for both "Source filter" and "Destination filter" and access to the currently active object should be provided.

For example, when editing the related VLAN-Group of a Device, the Device object data should be available for the destination filter using the following syntax:

```
{
  "location": "{{ source.location }}"
}
```

This would allow the destination filter to dynamically filter the available VLAN-Groups based on the device's location, ensuring that only relevant VLAN-Groups are presented to the user.

### So that ...

... enabling the ability to select only matching (device.location == vlan_group.location) entries, eliminating the need to sift through an extensive list that may not clearly indicate whether the necessary relationships are established.

### I know this is done when...

- I define a relationship (Filter values)
- I edit the relationships of an object.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- ?

### External Dependencies

None

**Comment by glennmatthews** [comment] 2024-02-05 16:51
Is this different from #1593?

**Comment by jifox** [comment] 2024-02-06 04:45
I think it's the same

**Comment by glennmatthews** [comment] 2024-09-09 21:43
Closing as a duplicate of #1593.

**Closed by glennmatthews** 2024-09-09 21:43 UTC
Labels: type: feature, triage
