### ISSUE TITLE
Profile highly-used model fields to see if they should have indexes added.

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#2780] opened 2022-11-08 21:55 UTC
### Proposed Changes

- Scan code base in how the field is commonly used in queries
- Perform similar queries using the field in scope and call `.explain()` on the queryset
- Take the output from `.explain()` and paste it into https://explain.depesz.com/
- See what, if anything, it suggests. If it is doing a table scan and not using an index, we might want to add `index=True` to the field
- We also might want to use `Meta.index_together` for other fields with which it is commonly queried.

Fields in scope:

```
$ grep -A1 -r "rofile filter.*index" nautobot
nautobot/dcim/models/cables.py:    # TODO: Profile filtering on this field if it could benefit from an index
nautobot/dcim/models/cables.py-    path = JSONPathField()
--
nautobot/dcim/models/devices.py:    # 2.0 TODO: Profile filtering on this field if it could benefit from an index
nautobot/dcim/models/devices.py-    u_height = models.PositiveSmallIntegerField(default=1, verbose_name="Height (U)")
--
nautobot/dcim/models/devices.py:    # 2.0 TODO: Profile filtering on this field if it could benefit from an index
nautobot/dcim/models/devices.py-    position = models.PositiveSmallIntegerField(
--
nautobot/dcim/models/devices.py:    # 2.0 TODO: Profile filtering on this field if it could benefit from an index
nautobot/dcim/models/devices.py-    vc_position = models.PositiveSmallIntegerField(blank=True, null=True, validators=[MaxValueValidator(255)])
```

- `Cable.path` 
- `DeviceType.u_height`
- `Device.position`
- `Device.vc_position`

### Justification

Scalable performance on commonly-used field lookups.

**Comment by bryanculver** [comment] 2022-11-09 02:10
So we had #1639 which resulted in #1793 and has a follow-up story #1861. How is this different?

**Comment by bryanculver** [comment] 2022-11-11 20:15
Dupe of #1861

**Closed by bryanculver** 2022-11-11 20:15 UTC
Labels: type: housekeeping
