### ISSUE TITLE
Issues with filtering by VLAN on the Locations list page

### ISSUE THREAD

**Issue by gioccher** [nautobot/nautobot#5923] opened 2024-07-11 19:49 UTC
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.7
* Python version: 3.9.17
* Database platform, version: MySQL
* Middleware(s):

### Steps to Reproduce
1. Open https://demo.nautobot.com/ipam/vlans/
2. Click on any number from the Locations column

and

1. Open https://demo.nautobot.com/dcim/locations/
2. Click on Filter
3. Click on Advanced
4. Select "Tagged VLANs (VID or ID)", "exact", and pick a specific vlan like "dfw01-103-mgmt"
5. Click Apply

### Expected Behavior
The locations page opens and shows locations for that specific vlan

### Observed Behavior
When coming from the VLANs page:
```
<class 'ValueError'>

Field 'vid' expected a number but got '01acc3fb-d449-4f36-9789-df5503206528'.

Python version: 3.11.9
Nautobot version: 2.2.7
```

When applying the filter in the Locations page:
all the locations for all the VLANs with the same VID are shown

**Comment by glennmatthews** [comment] 2024-07-11 20:49
Thanks for the report! I think this is a duplicate of #4229, for which a fix (#5737) has been made in `next` for the 2.3 release, e.g.:

https://next.demo.nautobot.com/dcim/locations/?vlans=01acc3fb-d449-4f36-9789-df5503206528

It wouldn't be difficult for someone to backport that fix to `develop` but given how close we are to the 2.3 release at this point I'm not sure the core team will make it a priority.

**Comment by gioccher** [comment] 2024-07-11 21:01
oh good!
Checking 2.3 it looks like the 2nd way to reproduce is still problematic:

  1. Open https://demo.nautobot.com/dcim/locations/
  1. Click on Filter
  1. Click on Advanced
  1. Select "Tagged VLANs (VID or ID)", "exact", and pick a specific vlan like "dfw01-103-mgmt"
  1. Click Apply

**Comment by HanlinMiao** [comment] 2024-07-12 14:47
Confirm the second behavior in next.demo, seems like selecting one specific vlan would select all the vlans available for some reason.
![Screenshot 2024-07-12 at 10 46 39 AM](https://github.com/user-attachments/assets/c2e5d145-10b0-4bba-9592-3ebeba5dd9e5)

**Comment by lampwins** [comment] 2024-07-12 18:28
We will fix the second scenario in next.

**Closed** 2024-07-19 15:04 UTC
Labels: type: bug
