### ISSUE TITLE
Inability to filter interfaces by device in Web UI

### ISSUE THREAD

**Issue by grahamjohnston** [nautobot/nautobot#4829] opened 2023-11-20 16:08 UTC
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.4

### Steps to Reproduce
1. Using the main interfaces page at, /dcim/interfaces/, filter the list of addresses by selecting a device from the default tab of the filter pop up.
2. Apply the filter.
3. Watch Nautobot filter by Device name but use UUID value.

### Expected Behavior
1. Either use UUID and Device ID, or leave it as device name for both.

### Observed Behavior
1. Nautobot is translating device name to UUID but still trying to filter against device name.
2. Device name filtering does work properly if one uses the Advanced tab.

**Comment by whitej6** [comment] 2023-11-20 16:19
Able to replicate in demo.nautobot.com an example is `https://demo.nautobot.com/dcim/interfaces/?device=37a938b0-bd5a-4c25-9d98-a51c75d15ba9` which is applying `ams01-edge-01` as a filter to interfaces.

**Comment by BoudewijnSwen** [comment] 2023-11-21 09:45
This sounds a lot like the issue I was coming here to report. Pretty much this same filtering issue occurs with cables and a rack filter.
So under dcim/cables/ --> apply filter: Rack x --> view becomes empty. (which it should not be...)

This for sure worked in the 1.x version we ran before. We are now on 2.0.4 as well.

**Comment by lampwins** [comment] 2024-02-02 21:34
Duplicate of https://github.com/nautobot/nautobot/issues/5059 and we will track it there.

**Closed by lampwins** 2024-02-02 21:34 UTC
Labels: type: bug
