### ISSUE TITLE
Device filter dialog dropdowns offset

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#3125] opened 2023-01-17 13:50 UTC
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.7
* Python version: 3.7
* Database platform, version: postgres
* Middleware(s):

The device filter (I suspect other filters as well) dialog displays dropdowns that are in the wrong location.

![Screenshot 2023-01-17 at 6 47 00 AM](https://user-images.githubusercontent.com/14947575/212915425-a292d737-7268-4561-b6ed-9d66347266f8.png)

### Steps to Reproduce
1.  Visit the [Nautobot Devices Page](https://demo.nautobot.com/dcim/devices/)
2.  Make sure you have a tall enough browser window to see the filter dialog
3.  Click filter
4. Scroll down to VLANs (or any filter towards the bottom of the page)
5. click the dropdown
6. Notice the choices are listed above VLANs, in the screenshot they are under device redundancy group priority

### Expected Behavior

The list of VLANs (or other dropdown) to filter by should be listed under the VLANs dropdown.

### Observed Behavior

Dropdowns towards the bottom of the filter dialog display choices in the wrong location on the screen.  Dropdowns towards the top of the list seem to behave better.

**Comment by glennmatthews** [comment] 2023-01-17 13:54
Possibly a duplicate of #3097, if so should be fixed in `develop` by #3098?

**Closed** 2023-01-17 14:49 UTC
Labels: type: bug
