### ISSUE TITLE
Error when loading device after deleting primary IP address

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot#3276] opened 2023-02-09 19:41 UTC
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.7, 1.5.10
* Python version: unknown (demo.nautobot.com)
* Database platform, version: unknown
* Middleware(s): unknown

### Steps to Reproduce
1. Create a device in Nautobot 
2. Create an interface for the device
3. Assign an IP address to the interface. Set it as the primary IP address for the device
4. Go to IPAM --> IP Addresses
5. Find the IP address you just created and assigned for the above device, and delete it
6. Go back to Devices --> Devices and load the newly created device.  It will crash.

### Expected Behavior
The device should load properly.  When deleting an IP address, it should unassign itself from any devices it is assigned to, including if it is assigned as a primary IP address.

### Observed Behavior
When deleting an IP address that is marked as a devices' primary IP, without first declassifying it as a primary IP, the device is unable to be loaded in the UI on the main tab.

NOTE: I can still load the device if I directly call it with another tab (ie. /interfaces/ instead of ?tab=main).  This leads me to believe the crash is occurring when trying to load the Primary IP for a device, but that IP Address object no longer exists.

**Comment by jifox** [comment] 2023-02-12 04:27
Duplicates: Error when accessing device detail page. #3096

https://github.com/nautobot/nautobot/issues/3096

**Comment by bryanculver** [comment] 2023-02-15 03:10
@matt852

Demo still has cacheops enabled. If you disable it in your environment does this issue persist?

**Comment by bryanculver** [comment] 2023-02-15 16:39
I cannot reproduce this locally with Cacheops disabled.

**Comment by bryanculver** [comment] 2023-02-15 23:12
Won't be fixed as is a Cacheops bug and that will be removed.

**Closed by bryanculver** 2023-02-15 23:12 UTC
Labels: type: bug
