### ISSUE TITLE
AttributeError when adding permissions to user

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#1298] opened 2022-01-24 08:40 UTC
### Environment
* Python version: 3.6.15
* Nautobot version: 1.2.4

Trying to add permissions directly to a user is not possible anymore. There is a workaround: add user to a permission (adding permission from the other side), but its tedious if you need to add more permissions than 1.

### Steps to Reproduce
1. Add permission to a user

### Expected Behavior
Permission added

### Observed Behavior
![image](https://user-images.githubusercontent.com/26114847/150748401-20cf284b-8726-44fa-86e1-148be67f299d.png)
<details>
  <summary>Complete traceback</summary>

```
[2022-01-24 08:34:33,712] ERROR django.request: Internal Server Error: /admin/users/user/c8705e7f-f534-5767-801c-71d37e2f9c18/change/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 192, in render
    return template.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/library.py", line 197, in render
    output = conditional_escape(output)
  File "/usr/local/lib/python3.6/site-packages/django/utils/html.py", line 102, in conditional_escape
    return text.__html__()
  File "/usr/local/lib/python3.6/site-packages/django/utils/html.py", line 377, in <lambda>
    klass.__html__ = lambda self: str(self)
  File "/usr/local/lib/python3.6/site-packages/django/utils/html.py", line 376, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.6/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget() + self.as_hidden(only_initial=True)
  File "/usr/local/lib/python3.6/site-packages/django/forms/boundfield.py", line 114, in as_hidden
    return self.as_widget(self.field.hidden_widget(), attrs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/forms/boundfield.py", line 97, in as_widget
    renderer=self.form.renderer,
  File "/usr/local/lib/python3.6/site-packages/django/forms/widgets.py", line 241, in render
    context = self.get_context(name, value, attrs)
  File "/usr/local/lib/python3.6/site-packages/django/forms/widgets.py", line 824, in get_context
    value = self.decompress(value)
  File "/usr/local/lib/python3.6/site-packages/django/forms/widgets.py", line 915, in decompress
    value = to_current_timezone(value)
  File "/usr/local/lib/python3.6/site-packages/django/forms/utils.py", line 181, in to_current_timezone
    if settings.USE_TZ and value is not None and timezone.is_aware(value):
  File "/usr/local/lib/python3.6/site-packages/django/utils/timezone.py", line 212, in is_aware
    return value.utcoffset() is not None
AttributeError: 'str' object has no attribute 'utcoffset'
```

</details>

**Comment by glennmatthews** [comment] 2022-01-24 13:32
Thanks for the report! I believe this is a duplicate of #1282; even though the steps to trigger this issue are different it's likely the same underlying cause.

**Closed by glennmatthews** 2022-01-24 13:32 UTC
