### ISSUE TITLE
Fresh install bombs on user edit

### ISSUE THREAD

**Issue by berlincount** [nautobot/nautobot#1296] opened 2022-01-22 22:33 UTC
### Environment

Python version: 3.9.9
Nautobot version: 1.2.4

### Steps to Reproduce
1. Install nautobot per helm3
2. Login as superuser
3. Create other user
4. Edit other user, give all permissions, whatever
5. Save user
6. Boom

### Expected Behavior

User edit is saved and usable.

### Observed Behavior

User edit is not saved. Instead:

```
<class 'AttributeError'>

'str' object has no attribute 'utcoffset'

Python version: 3.9.9
Nautobot version: 1.2.4
```

Slack access not available and no invite link given.

Further debug trace (unabbreviated):

```
22:18:20.828 ERROR   django.request :
  Internal Server Error: /admin/users/user/71f915f7-58ca-4072-9f7d-6b5f7c09deb8/change/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 192, in render
    return template.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/library.py", line 197, in render
    output = conditional_escape(output)
  File "/usr/local/lib/python3.9/site-packages/django/utils/html.py", line 102, in conditional_escape
    return text.__html__()
  File "/usr/local/lib/python3.9/site-packages/django/utils/html.py", line 377, in <lambda>
    klass.__html__ = lambda self: str(self)
  File "/usr/local/lib/python3.9/site-packages/django/utils/html.py", line 376, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.9/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget() + self.as_hidden(only_initial=True)
  File "/usr/local/lib/python3.9/site-packages/django/forms/boundfield.py", line 114, in as_hidden
    return self.as_widget(self.field.hidden_widget(), attrs, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/forms/boundfield.py", line 93, in as_widget
    return widget.render(
  File "/usr/local/lib/python3.9/site-packages/django/forms/widgets.py", line 241, in render
    context = self.get_context(name, value, attrs)
  File "/usr/local/lib/python3.9/site-packages/django/forms/widgets.py", line 824, in get_context
    value = self.decompress(value)
  File "/usr/local/lib/python3.9/site-packages/django/forms/widgets.py", line 915, in decompress
    value = to_current_timezone(value)
  File "/usr/local/lib/python3.9/site-packages/django/forms/utils.py", line 181, in to_current_timezone
    if settings.USE_TZ and value is not None and timezone.is_aware(value):
  File "/usr/local/lib/python3.9/site-packages/django/utils/timezone.py", line 212, in is_aware
    return value.utcoffset() is not None
AttributeError: 'str' object has no attribute 'utcoffset'
[pid: 18|app: 0|req: 86/286] 10.0.1.1 () {70 vars in 1552 bytes} [Sat Jan 22 22:18:20 2022] POST /admin/users/user/71f915f7-58ca-4072-9f7d-6b5f7c09deb8/change/ => generated 1840 bytes in 75 msecs (HTTP/1.1 500) 7 headers in 376 bytes (1 switches on core 0)
```

Logging in with the corresponding user once doesn't help.

TIA :)

**Comment by glennmatthews** [comment] 2022-01-24 13:31
Thanks for the report! I believe this is a duplicate of #1282; even though the steps to trigger this issue are slightly different it's likely the same underlying cause.

**Closed by glennmatthews** 2022-01-24 13:31 UTC
