### ISSUE TITLE
Crash: Updating status of device with primary IP address configured

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot#317] opened 2021-04-14 13:46 UTC
### Environment
* Python version: 3.6.13
* Nautobot version: 1.0.0b3

A 500 error page is returned if you try to edit the status of a device with a Primary IP address attached.  This error does not occur if either the device has no IP addresses assigned to it at all, or has one or more IP addresses assigned to it, but none are set as the Primary IP address.

I was able to replicate this on a fresh install, as well as in our demo environment https://develop.demo.nautobot.com/

### Steps to Reproduce
1.  Open any device with a primary IP address (ams-edge-01 in above demo site, for example)
2.  Click Edit
3.  Change the assigned Status, and click Save

To reproduce expected results:
1.  In DCIM-->Devices, select a Primary IP address assigned to a device (10.11.192.0/32 for ams-edge-01 for above demo site, for example)
2. Click Edit
3. Uncheck "Make this the primary IP for the device/VM" and Save
4. Open the device in DCIM-->Devices (ams-edge-01 in above demo site, for example)
5. Click Edit
6. Change the assigned Status, and click Save

### Expected Behavior
The status should update correctly.

### Observed Behavior
A 500 crash page appears with the following traceback:

```
<class 'AttributeError'>

'IPAddress' object has no attribute 'ip'

Python version: 3.6.13
Nautobot version: 1.0.0b3
```

**Comment by matt852** [comment] 2021-04-14 14:31
This does NOT appear to be an issue in Nautobot v1.0.0b2

**Comment by glennmatthews** [comment] 2021-04-14 14:50
Thanks for the report! This may be a duplicate of #300. Can you confirm whether this issue is still seen with the latest `develop` code base (containing #301)?

**Comment by jathanism** [comment] 2021-04-14 14:57
This is fixed in #300 for sure. Same issue, but will be good to get the confirmation from @matt852. Thanks! :)

**Comment by matt852** [comment] 2021-04-14 19:34
@glennmatthews @jathanism This looks to be fixed using the most recent updates in branch `develop`

**Comment by glennmatthews** [comment] 2021-04-14 20:38
Thank you for the confirmation!

**Closed by glennmatthews** 2021-04-14 20:38 UTC
Labels: question, type: bug
