### ISSUE TITLE
Filters on dynamic filter form are overridden by default filter form, and vice versa.

### ISSUE THREAD

**Issue by timizuoebideri1** [nautobot/nautobot#2756] opened 2022-11-07 14:45 UTC
### Environment
* Nautobot version (Docker tag too if applicable): next , 1.5
* Python version: 3.7+

### Steps to Reproduce
1. Click "Filter", then "Advanced" and input an advanced filter such as "name regex = ^ams01".
2. Click "Apply"
3. Observe that the filter name__re=^ams01 is displayed in list view
4. Click "Filter" again, then select any "Default" filter such as "has interfaces = Yes"
5. Click "Apply"

### Expected Behavior
New filters of the default filter form are applied in addition to the previously used advance filter filters.

### Observed Behavior
The previous filter was replaced and that only has_interfaces=True is displayed in list view.

**Comment by gsnider2195** [comment] 2022-11-09 15:36
Duplicate of #2732

**Closed** 2022-11-11 16:10 UTC
Labels: type: bug
