### ISSUE TITLE
Relationships appear as null on Devices

### ISSUE THREAD

**Issue by bryanward-net** [nautobot/nautobot#338] opened 2021-04-19 17:41 UTC
### Environment
* Python version: demo.nautobot.com
* Nautobot version: 1.0.0b3

### Steps to Reproduce
1. Create VLAN Group named "MyVLANGroup"
2. Create One-to-Many Relationship "dcim:device->ipam:VLAN group" named "Device to VLAN Group"
3. Create new Device named "MyDevice"
4. Edit device "MyDevice".  Assign "MyVLANGroup" to the "VLAN Group" Relationship of "My Device", click Update.
5. Note that the assignment of the VLAN Group relationship does not appear on the device info page, nor in the edit view of the device - it appears as null instead.  (Same issue seems to be present for VLAN Relationships as well, possibly others.)

### Expected Behavior
Expected to see the VLAN Group that was assigned appear in the Relationships section of the device

### Observed Behavior
Relationships->VLAN Group appears as null for the device

**Comment by glennmatthews** [comment] 2021-04-19 18:09
Thank you for the report! I'm unable to reproduce this issue in the latest `develop` code, which leads me to believe this issue was probably fixed by #321 or one of the other Relationship fixes we've made very recently.

![image](https://user-images.githubusercontent.com/5603551/115282386-2bbc9b80-a118-11eb-831a-eb9ec826a9f7.png)
![image](https://user-images.githubusercontent.com/5603551/115282647-6fafa080-a118-11eb-8683-a805c4b2d6a1.png)

**Comment by jedelman8** [comment] 2021-04-29 14:52
@bryanward-net can you confirm this is still an issue?

**Comment by glennmatthews** [comment] 2021-06-17 16:39
Closing this as believed to be resolved. If the issue is encountered again, feel free to comment here or re-open the issue. Thank you!

**Closed by glennmatthews** 2021-06-17 16:39 UTC
Labels: pending closure, question, status: under review
