### ISSUE TITLE
"docker-compose: command not found" when running invoke commands on ltm-1.6

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#5336] opened 2024-02-23 15:09 UTC
### Environment
* Nautobot version (Docker tag too if applicable): v1.6.12
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Install a recent version of docker
2. Run "invoke debug"

### Expected Behavior
Nautobot starts

### Observed Behavior
```
Starting Nautobot in debug mode...
Running docker-compose command "up"
PYTHON_VER=3.9 \
docker-compose \
    --project-name "nautobot" \
    --project-directory "/home/gary/github/nautobot/development" \
    -f "/home/gary/github/nautobot/development/docker-compose.yml" \
    -f "/home/gary/github/nautobot/development/docker-compose.postgres.yml" \
    -f "/home/gary/github/nautobot/development/docker-compose.dev.yml" \
    -f "/home/gary/github/nautobot/development/docker-compose.override.yml" up
/bin/bash: line 1: docker-compose: command not found
(nautobot-DIHtVAwE-py3.11) gary@debian:~/github/nautobot (ltm-1.6)$ vi ~/.bashrc
(nautobot-DIHtVAwE-py3.11) gary@debian:~/github/nautobot (ltm-1.6)$ vi ~/.bashrc
(nautobot-DIHtVAwE-py3.11) gary@debian:~/github/nautobot (ltm-1.6)$ docker-compose() { docker compose "$@"; }
(nautobot-DIHtVAwE-py3.11) gary@debian:~/github/nautobot (ltm-1.6)$ inv debug
Starting Nautobot in debug mode...
Running docker-compose command "up"
PYTHON_VER=3.9 \
docker-compose \
    --project-name "nautobot" \
    --project-directory "/home/gary/github/nautobot/development" \
    -f "/home/gary/github/nautobot/development/docker-compose.yml" \
    -f "/home/gary/github/nautobot/development/docker-compose.postgres.yml" \
    -f "/home/gary/github/nautobot/development/docker-compose.dev.yml" \
    -f "/home/gary/github/nautobot/development/docker-compose.override.yml" up
/bin/bash: line 1: docker-compose: command not found
```

**Comment by glennmatthews** [comment] 2024-02-23 15:15
Duplicate of #2207?

**Closed** 2024-02-26 14:06 UTC
Labels: type: bug, emergent
