### ISSUE TITLE
Dynamic group creation with name filter through `nbshell` doesn't work correctly

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot#2713] opened 2022-11-02 14:03 UTC
### Environment
* Nautobot version 1.4.5 + 6d038f620d347716ca625f448da2d044183a9dd5
* Python version: 3.9 and 3.10
* Database platform, version: PostgreSQL 13
* Middleware(s): -

### Steps to Reproduce

1.
```
$ nautobot-server nbshell
>>> dg = DynamicGroup(name="Testing")
>>> dg.filter = {"name": "Test"}
>>> dg.content_type = ContentType.objects.get_for_model(Device)
>>> dg.validated_save()
```
2. Navigate to the detail page of the dynamic group in the GUI
3. (optional) Edit + save via the GUI resolves the issue. Note: The issue also affects the actual filtering behavior, its not just a visual bug

### Expected Behavior
The filter to be
```
(
  name='Test'
)
```

### Observed Behavior
![Screenshot 2022-11-02 at 15 01 16](https://user-images.githubusercontent.com/12400533/199509146-7ed0a3a3-7e55-478a-8a8c-39159407f7d3.png)

**Comment by glennmatthews** [comment] 2022-11-02 14:09
Most filters are multi-value filters, I suspect that you should instead be passing `filter = {"name": ["Test"]}`

**Comment by Kircheneer** [comment] 2022-11-02 14:20
I can confirm that works. That leaves the following two questions:
- Can we throw an error when users try to pass a `str` type to that filter field?
- Why does it fix itself if I hit edit and save in the GUI without changing anything in the form? Is that expected behavior?

**Comment by jathanism** [comment] 2022-11-02 18:36
> I can confirm that works. That leaves the following two questions:
> 
> * Can we throw an error when users try to pass a `str` type to that filter field?
> * Why does it fix itself if I hit edit and save in the GUI without changing anything in the form? Is that expected behavior?

This is default behavior that was changed between versions of Nautobot. Support for multi-value char filtering was added in Nautobot 1.4 so this is unfortunately a side effect of having changed this from a single value to multi-value field.

The problem is that the UI widget to support this won't be fixed until 1.5 release.

The plus side is now you can implement `name` filters for more that one value. And in v1.5 that will actually be reflected correctly in the widget for the UI edit forms.

**Comment by jathanism** [comment] 2022-11-02 18:44
I think I might have a solution though...

**Comment by jathanism** [comment] 2022-11-04 16:25
Actually my idea didn't work and it's a side effect from the `NewField` class inside of the `multivalue_field_factory()`, which is secretly turning a single value into a list internally:

https://github.com/nautobot/nautobot/blob/e73d25c06761dbe73fed29d4d16fa13b1af27255/nautobot/utilities/filters.py#L49-L51

If you were to try to save a single string value on another field, such as `location`, you correctly get a validation error:

```python
In [4]: dg.filter = {'location': 'location-a'}

In [5]: dg.validated_save()
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In [5], line 1
----> 1 dg.validated_save()

File ~/sandbox/src/nautobot/nautobot/core/models/__init__.py:51, in BaseModel.validated_save(self)
     40 def validated_save(self):
     41     """
     42     Perform model validation during instance save.
     43
   (...)
     49     command.
     50     """
---> 51     self.full_clean()
     52     self.save()

File ~/Library/Caches/pypoetry/virtualenvs/nautobot-b2ttWva6-py3.10/lib/python3.10/site-packages/django/db/models/base.py:1251, in Model.full_clean(self, exclude, validate_unique)
   1248         errors = e.update_error_dict(errors)
   1250 if errors:
-> 1251     raise ValidationError(errors)

ValidationError: {'location': ['Enter a list of values.']}
```

**Comment by jathanism** [comment] 2022-11-04 17:05
> Thought: You shouldn't edit the filter directly and instead we should have a simplified interface of taking in a valid filterset/filterform.

We actually already have that!

```
In [4]: dg.set_filter({"name": "ams01-dist-01"})

In [5]: dg.filter
Out[5]: {'name': ['ams01-dist-01']}

**Closed** 2022-11-09 17:44 UTC
Labels: type: bug
