### ISSUE TITLE
Decouple VLAN from 1-4094 ID Integer

### ISSUE THREAD

**Issue by kingfetty** [nautobot/nautobot#1640] opened 2022-04-14 20:09 UTC
### As ...

Nelly - Network Engineer

### I want ...

Modern SDN systems are starting to or already abstract the layer 2 domain to a name rather than the assigned VLAN Id integer.  While internally the switching hardware may use the VLAN ID to segment traffic, the ID may be dynamic or unknown to the engineers.  This makes tracking layer 2 domains that use Names instead of IDs incompatible with the current Nautobot data model.

I would like to see the Nautobot tool modified to be able track layer 2 domains agnostic to the VLAN ID integer. 

### So that ...

we can use the Nautobot system as network source of truth in our SDN environments without having to product some sort of weird workaround.

### I know this is done when...

The nautobot tool can track layer 2 domains without enforcing the VLAN ID.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [X] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

In order to do this, the vlan ID field would have to be not mandatory and would not be the primary key for the data structure.

**Comment by bryanculver** [comment] 2022-05-31 19:42
Duplicate of #915

**Closed by bryanculver** 2022-05-31 19:42 UTC
Labels: workflow: under review, type: feature, group: ipam
