### ISSUE TITLE
Extending filtering of date custom field type

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#1498] opened 2022-03-15 14:25 UTC
### As ...

Dan - Data Owner

### I want ...

to filter data by before/after custom field of type `date`

### So that ...

I can find all devices whose warranty will expire after certain date. Warranty is only one of 5 dates we have as custom field.

### I know this is done when...

- ~Using `loose` filtering condition allows for these extensive filters and does not behave same way as `exact`~
  - `loose` and `exact` filtering of custom fields is an old concept that we will be moving away from.
- I am able to filter custom fields by before/after some date via API
- I am able to filter custom fields by before/after some date via changing parameter in URL
- (further discussion needed) I am able to filter custom fields by before/after some date via GUI

Date/time custom fields should use the same lookup expression filters as concrete fields.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [X] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

None most probably

**Comment by glennmatthews** [comment] 2022-03-15 14:51
Possible duplicate of #1288.

**Comment by jathanism** [comment] 2022-04-28 14:53
IMO the `range` filter should be implemented on `Date` filter types across the board!

**Comment by bryanculver** [comment] 2022-08-08 13:20
Closed with #2126

**Closed by bryanculver** 2022-08-08 13:20 UTC
Labels: type: feature
