### ISSUE TITLE
Manufacturers page does not update correctly

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot#1627] opened 2022-04-11 16:18 UTC
### Environment
* Python version: Unknown (on demo.nautobot.com)
* Nautobot version: 1.2.9

### Steps to Reproduce
1. Log in to demo.nautobot.com
2. Go to Devices --> Manufacturers
3. Note the current number of device types for Arista and Cisco (currently Arista = 5, Cisco = 4)
4. Go to Devices --> Device Types
5. Edit Device Type "TestManufacturersBug" and change its Manufacturer from `Arista` to `Cisco`. Save.
6. Go back to Devices --> Manufacturers.  The Device Type count remains as before (Arista = 5, Cisco = 4). Refreshing/hard refreshing does not fix this.
7. Click on the "Add" button, and create a new Manufacturer (name doesn't matter). Click save.
8. Once saved, the page will refresh with the new manufacturer, and the numbers for Arista and Cisco will be updated accurately (Arista = 4, Cisco = 5).  Note this refresh also works when editing any existing manufacturer, or deleting an existing one.

### Expected Behavior
When updating the Manufacturer for a Device Type, the count should be updated accordingly on the Devices --> Manufacturers page.

### Observed Behavior
The count is not updated until a database modification is made to the Manufacturers table (add, change or delete will all update the count).

**Comment by glennmatthews** [comment] 2022-04-11 16:49
Thanks for the report! Sounds suspiciously like (yet another) cacheops issue to me.

**Comment by matt852** [comment] 2022-04-21 14:18
An identical issue also appears to exist for IPAM Roles.  Would you like a separate issue created for this, or leave it in here?

**Comment by glennmatthews** [comment] 2022-04-21 14:52
It's almost certainly the same root cause (both views are using the `count_related` utility function) so I'd vote for just adding the IPAM steps-to-reproduce to this issue as well.

**Comment by matt852** [comment] 2022-04-21 15:01
### Steps to Reproduce

1. Log in to demo.nautobot.com
2. Go to IPAM --> Prefix/VLAN Roles
3. Note the current number of device types for `testrole1` and `testrole1` (currently testrole1 = 1, testrole2 = 0)
4. Go to IPAM --> Prefixes
5. Edit Prefix `192.168.255.0/30` and change its Role from `testrole1` to `testrole2`. Save.
6. Go back to  IPAM --> Prefix/VLAN Roles. The Prefixes count remains as before (testrole1 = 1, testrole2 = 0). Refreshing/hard refreshing does not fix this.
7. Click on the "Add" button, and create a new Role (name doesn't matter). Click save.
8. Once saved, go back to IPAM --> Prefix/VLAN Roles, and the numbers for `testrole1` and `testrole2` will be updated accurately (testrole1 = 0, testrole2 = 1).  Note this refresh also works when editing any existing role, or deleting an existing one.

**Comment by matt852** [comment] 2022-07-06 18:55
I found this affects Device Type count as well.  Adding to the list.

**Steps to Reproduce**

1. Log in to demo.nautobot.com
2. Go to Devices --> Device Types
3. Note the current number of device types for DCS-7048-T and vEOS (currently DCS-7048-T = 1, vEOS = 4)
4. Go to Devices --> Devices
5. Edit Device "wee-eos7k-01.nautobot.com" and change its Device Type from DCS-7048-T to vEOS. Save.
6. Go back to Devices --> Device Types. The Instances count remains as before (DCS-7048-T = 1, vEOS = 4). Refreshing/hard refreshing does not fix this.
7. Click on the "Add" button, and create a new Device Type (name/data doesn't matter). Click save.
8. Once saved, the page will refresh with the new device type, and the numbers for DCS-7048-T and vEOS will be updated accurately (DCS-7048-T = 0, vEOS = 5). Note this refresh also works when editing any existing device type, or deleting an existing one.

**Comment by bryanculver** [comment] 2023-02-14 20:48
This will be resolved with the removal of Cacheops (confirmed fixed with 1.5). #1721

**Closed by bryanculver** 2023-02-14 20:48 UTC
Labels: type: bug
