### ISSUE TITLE
Inability to search by UUID

### ISSUE THREAD

**Issue by david-kn** [nautobot/nautobot#1506] opened 2022-03-16 15:46 UTC
### Environment
* Python version: -
* Nautobot version: 1.2.7

### Steps to Reproduce
1. Use object UUID for search in Nautobot GUI search field

### Expected Behavior
Object with given UUID should be found and returned in results.

### Observed Behavior
Either non results or irrelevant IP address object is the only returned as a "matching" result.

**Comment by glennmatthews** [comment] 2022-03-16 19:38
This may be a duplicate of #923?

**Comment by david-kn** [comment] 2022-03-16 19:50
Yes, please. 
Sorry for this duplicate. I somehow didn't notice it although I tried to search (honestly, only quickly) for such a topic.

**Closed** 2022-03-16 19:50 UTC
Labels: workflow: under review
