### ISSUE TITLE
Persistent vertical scrollbar

### ISSUE THREAD

**Issue by u1735067** [nautobot/nautobot#711] opened 2021-07-16 13:54 UTC
### Environment
* Python version: 3.9
* Nautobot version: 1.0.3

### Steps to Reproduce
1. Open login page (https://demo.nautobot.com/login/)
2. Maximise the browser so that there should be no need for scrollbar

### Expected Behavior
No vertical scrollbar

### Observed Behavior
A vertical scrollbar for a few pixels is present

### Additional informations
This seems to be caused by the footer at `/html/body/footer/div/div/div[3]/p` (icon part, `p` with `text-muted` class) ; a fix would to to change `footer p { margin: 12px 0; }` by `footer p { margin: 12px 0 0 0; }` in https://github.com/nautobot/nautobot/blob/v1.0.3/nautobot/project-static/css/base.css#L31.

This is also an issue in Netbox (and was previously fixed in https://github.com/nautobot/nautobot/commit/8f4197c0207dd9467dc09b8e89dfcd896b2c8a79 for issue 5518, but I can still see it).

**Comment by jathanism** [comment] 2021-07-20 14:01
Thanks for the report and the recommend fix. Much appreciated! :)

**Comment by glennmatthews** [comment] 2021-08-16 21:03
Hi @u1735067 , could you perhaps provide a screenshot of the issue you are seeing, and let us know which browser you are seeing this issue with? The only behavior I see on my computer is that the vertical scrollbar is always present (but not necessarily scrollable) on all Nautobot pages, which is caused by the global `html { overflow-y: scroll }` setting in `base.css`. Are you asking for this setting to be changed so that the scrollbar only appears when actually needed? (I'm not necessarily opposed to this change, but I want to make sure I understand what is being requested!) Or is there some other detail that I'm not following?

**Comment by glennmatthews** [comment] 2021-08-16 21:06
Default behavior (with unnecessary vertical scrollbar):

![image](https://user-images.githubusercontent.com/5603551/129629340-166c80ce-da05-4878-bb75-6a067b38d2b2.png)

After removing `overflow-y: scroll`:

![image](https://user-images.githubusercontent.com/5603551/129629401-45b658f2-025d-44a3-aa11-3b7d31b9615d.png)

**Comment by glennmatthews** [comment] 2021-08-16 21:08
Perhaps relevant: https://github.com/netbox-community/netbox/pull/283

**Comment by u1735067** [comment] 2021-08-17 08:55
> Hi @u1735067 , could you perhaps provide a screenshot of the issue you are seeing, and let us know which browser you are seeing this issue with?

Sure!

![recording](https://user-images.githubusercontent.com/1735067/129693227-bb8af058-ef29-44e8-87f8-4e625d79a7f4.gif)

I've seen this with both Chrome (92.0.4515.131) and Firefox (78.13.0esr) .. However while I'm able to reproduce on different browsers on the same computer, I've not been able to reproduce on another computer so I'm not sure what to think about this ..

The issue is probably on my side so close this if you want. For the record I had another issue with the menu buttons messing up but only in Chromium based browsers on a HiDPI screen (move the window to a 100% scaled screen and the layout becomes ok), I was able to link it to https://bugs.chromium.org/p/chromium/issues/detail?id=1162226#c8 (you can see the result), but for the scrollbar it doesn't seems to be specific to a screen nor a browser 😶

> The only behavior I see on my computer is that the vertical scrollbar is always present (but not necessarily scrollable) on all Nautobot pages, which is caused by the global `html { overflow-y: scroll }` setting in `base.css`. Are you asking for this setting to be changed so that the scrollbar only appears when actually needed? (I'm not necessarily opposed to this change, but I want to make sure I understand what is being requested!) Or is there some other detail that I'm not following?

No it's not about this, sorry if I made you spend time on this, I though it was reproducible and omit to include a screencast.

**Comment by glennmatthews** [comment] 2021-08-17 16:43
Thank you for the prompt and detailed response! I'll leave this open for a bit longer to see if I can find anyone to reproduce it on Windows or Linux (I was testing on my Mac).

**Comment by carbonarok** [comment] 2021-08-18 17:37
Tried to replicate issue on multiple browers (mac and windows) with no success. Thanks for opening the issue @u1735067, we can reopen the issue if it persists.

Closing issue as unable to reproduce.

**Closed by carbonarok** 2021-08-18 17:37 UTC
Labels: type: bug, status: accepted

**Comment by u1735067** [comment] 2021-08-19 08:19
I finally found what is causing this issue and how to reproduce: I happen to have the font `Helvetica Neue` installed on this computer, font referenced in https://github.com/nautobot/nautobot/blob/v1.1.2/nautobot/project-static/bootstrap-3.4.1-dist/css/bootstrap.css#L1085.

Disabling this font makes the scrollbar inactive as expected:

![recording (3)](https://user-images.githubusercontent.com/1735067/130033657-ec45ea8e-a8b3-449e-ae87-5d1cbe00f895.gif)

It also fixes my issue with the menu buttons : 

![recording (2)](https://user-images.githubusercontent.com/1735067/130033348-56b03b3b-6064-41ad-8a0b-9516faa785d0.gif)

Can you reopen?

**Comment by glennmatthews** [comment] 2021-08-19 13:43
Fascinating find! It looks like this is a known issue with "Helvetica Neue" on Windows:

- https://github.com/twbs/bootstrap/issues/13823
- https://github.com/twbs/bootstrap/issues/13840
- https://blog.presentation-company.com/avoid-this-font

Given that, I'm surprised to see that even the latest versions of Bootstrap are still including Helvetica Neue as a font option - their position appears to be that "Windows users shouldn't ever have this font installed, as it's a Mac-specific font", which is certainly an *interesting* position to take...

**Comment by u1735067** [comment] 2021-08-19 15:35
I didn't went that far but interesting discussions yes ..

To add more informations and close this topic, as some replies seems to imply the font might be misinstalled, in my case I have the font in version 4.00 (licenced to corp, maybe a variant?) installed in 5 weight (35, 45, 55, 65, 75): 
![image](https://user-images.githubusercontent.com/1735067/130097673-31ec4832-155e-4ad0-9860-baf467469eef.png)

I tried to install https://chrome.google.com/webstore/detail/remove-helvetica-neue/aebieeaodhkabdnmhjbfmdohhhcoipof but it doesn't seem to be working.

Not a big deal now I know why, maybe I'll remove it. Thanks for finding theses posts.
