### ISSUE TITLE
Provide Changelog entries to standard python logging

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#3031] opened 2022-12-20 15:04 UTC
### As ...

Austin - Network Automation Engineer

### I want ...

to be able to track changes to the Nautobot objects for the long term

### So that ...

I can audit and trace changes in Nautobot beyond the database retention period.  We have a large volume of automation changes occurring in the Nautobot database with SSOT and other tools.  This creates a retention issue for us with our database team would only like to store short term change logs in the database say < 10 days.  We would like to simply echo the same change information to the logs (via the python logger is fine) for us to capture in our longer term data lake (ELK in our case but could be splunk or others).

### I know this is done when...

- I have changelog entries in the database echo'd to the python logger

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

None

### External Dependencies

- logging

**Comment by chadell** [comment] 2023-11-02 08:53
@glennmatthews , this could include also `JobResults` (JobHistory) because both logs are interesting to extract

**Comment by glennmatthews** [comment] 2024-09-11 18:32
Duplicate of #3180

**Closed by glennmatthews** 2024-09-11 18:32 UTC
Labels: type: feature
