### ISSUE TITLE
Unify optional settings documentation for REMOTE_AUTH*/SOCIAL_AUTH*

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#149] opened 2021-03-15 15:11 UTC
### Proposed Changes

Currently, the documentation for setting up default groups/permissions for remotely-authenticated users is either duplicated or spread out across the documentation for [Remote User Authentication](https://nautobot.readthedocs.io/en/latest/configuration/authentication/remote/#configuration) and [SSO Authentication](https://nautobot.readthedocs.io/en/latest/configuration/authentication/sso/#configuration).

We should fix that and, move them to be documented to a single location and reference those docs from each authentication guide.

### Justification

Currently it's not clear on whether these settings would also work with LDAP or other forms of authentication, but they absolutely should. The documentation makes it seem as if these are distinct and there are different ways. Additionally the LDAP documentation does not cover or link to these configuration settings at all.

**Comment by dgjustice** [comment] 2021-03-15 16:41
@jathanism I'll take a look at this one.

**Comment by jathanism** [comment] 2021-03-15 16:43
@dgjustice You're hired!

**Comment by dgjustice** [comment] 2021-03-16 20:54
@jathanism @glennmatthews This was committed 19 days ago.  https://github.com/nautobot/nautobot/commit/15fd3b482dcbedc41e120ac171ce1fafd26e34b6

I'm not sure what the ask needs to be.  It appears to me like `SOCIAL_AUTH_DEFAULT_GROUPS` and `SOCIAL_AUTH_DEFAULT_PERMISSIONS` and `SOCIAL_AUTH_POSTGRES_JSONFIELD` are declared but never used.  Should I first go down the rabbit hole of setting up all these various options to see what works and doesn't (maybe even what conflicts and doesn't), and _then_ document my findings?  My naïve initial approach was to dedup the docs, but it appears there are other flies in the ointment.

**Comment by dgjustice** [comment] 2021-03-24 15:13
I guess this issue is a duplicate of #18

**Closed** 2021-03-30 19:49 UTC
Labels: status: current, type: documentation, type: housekeeping
