### ISSUE TITLE
Role UI should only display tables of allowed content types

### ISSUE THREAD

**Issue by scetron** [nautobot/nautobot#4703] opened 2023-10-24 20:46 UTC
### As ...

Ozzie - Operator

### I want ...

I want the Role detail view to display only relevant related objects.

### So that ...

So that the display is cleaner, uncluttered, and less confusing. 

### I know this is done when...

- I can view the Role detail screen and see tables/headers only for objects that are allowed in the allowed content types for the Role.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [X] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

n/a. Should only be some conditional syntax in the template?

### External Dependencies

None.

**Comment by glennmatthews** [comment] 2023-10-24 20:49
Duplicate of #4026?

**Comment by scetron** [comment] 2023-10-24 20:54
Yes.

**Closed** 2023-10-24 20:58 UTC
Labels: type: feature, triage
