### ISSUE TITLE
Limit UI/UX export to showed columns

### ISSUE THREAD

**Issue by jakubkrysl** [nautobot/nautobot#1499] opened 2022-03-15 14:37 UTC
### As ...

Ozzie - Operator

### I want ...

to export exactly what I see in my configured table view

### So that ...

it is easier for me to work with exported data and I can export only required data and don't have to remove other columns.

### I know this is done when...

- Exporting data allows me to export only columns I have configured

This does not have to be breaking change, some small switch could allow me to export all or only chosen columns.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

None

### External Dependencies

None

**Comment by glennmatthews** [comment] 2024-10-04 20:18
Closing this as a duplicate of #4373.

**Closed by glennmatthews** 2024-10-04 20:18 UTC
Labels: type: feature
