### ISSUE TITLE
Hide Nautobot version in footer for unauthenticated users

### ISSUE THREAD

**Issue by Jonher937** [nautobot/nautobot#2682] opened 2022-10-25 12:19 UTC
### As ...

Isabella - Infrastructure Owner

### I want ...

the Nautobot version to be hidden on the navigating pages unless the user is logged in

### So that ...

we comply with company policies

### I know this is done when...

- The version is not displayed on the front-page unless the user is authenticated

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

- None

### External Dependencies

- None

**Comment by Kircheneer** [comment] 2022-10-25 12:36
Duplicate of #1704? Also see this #1610

**Closed** 2022-11-01 13:02 UTC
Labels: type: feature
