### ISSUE TITLE
No way to link VRFs to prefixes or IP addresses through Ansible or API

### ISSUE THREAD

**Issue by chris-tomkins-flexgrid** [nautobot/nautobot#5219] opened 2024-02-02 12:28 UTC
##### ISSUE TYPE
 - Bug Report

###### pynautobot
2.0.2

###### Ansible:
core 2.16.0

###### Nautobot:
2.1.2

###### Collection:
5.1.1

##### SUMMARY
There appears to be no way to link VRFs to prefixes or IP addresses through Ansible or API. Checking the built-in API docs and the Ansible collection docs, it is possible to create a prefix or IP address object with a "Namespace" assigned, but not a "VRF". Similarly, a VRF object can be created but there is no way to assign a prefix or IP address to it.

I also tried creating a "Relationship" as you would for something like a software version to device mapping, and although the relationship is seen in the GUI, it does not create an "official" link between the two objects consistent to what you get if you assign a prefix in the GUI.

##### STEPS TO REPRODUCE
- name: Creating prefix records
  networktocode.nautobot.prefix:
    prefix: "{{wansubnetusuallyslash29}}/{{wansubnetnonstandardmask}}"
    location:
      name: "{{nautobot_site}}"
    namespace: "VRF Namespace Internet"
    ******vrf: "Internet"******
    state: present
    status: "{{'Active' if not awaitingfirstprovision else 'Reserved'}}"
    tags:
      - "Record edited by Ansible"
    tenant: "{{nautobot_tenant}}"
    token: "{{nautobot_read_write_token}}"
    type: Container
    url: https://{{nautobot_api_ip}}

##### EXPECTED RESULTS
I would expect the prefix or IP address to be created assigned to both the namespace and VRF as shown.

##### ACTUAL RESULTS
The above fails as VRF is not a valid argument.

**Comment by glennmatthews** [comment] 2024-02-02 15:20
We need a dedicated REST API endpoint for managing the VRFPrefixAssignment M2M table.

**Comment by lampwins** [comment] 2024-02-02 19:51
Turns out this is a duplicate of #4270. We will track this there.

**Closed by lampwins** 2024-02-02 19:51 UTC
Labels: type: bug
