### ISSUE TITLE
Spike: Investigate GraphWrap to see if it is worth implementing

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#784] opened 2021-08-05 17:07 UTC
### Proposed Changes

I am proposing that we perform a spike with the intent of determining whether it would be feasible and valuable to implement [GraphWrap](https://github.com/PaulGilmartin/graph_wrap) to replace our custom schema generation code in `nautobot.core.graphql`. 

No more than a day should be spent attempting to implement GraphWrap and to identify and assess how it compares to our current custom implementation. The outcome of this spike should be a decision and a level of effort estimation to the tactical steps required to move forward.

### Justification

While our current implementation works for the common case there are a growing number of edge cases that we have yet to solve (See: #446, #596, #464). The GraphWrap library appears to do largely the same thing, but requires almost no code on our side "by adding only two lines of code to your django project" (according to the project documentation).

GraphWrap is also fully tested. Ideally, it would result in us having approximately 600 fewer lines of code to maintain, but it remains to be seen whether we would still get the desired behavior we want. All the same, from a maintainability perspective, it would be better to contribute upstream to an already established project than to continue to maintain our own implementation.

### Acceptance Criteria

- [x] Evaluate if we no longer need to restart to update schema changes
- [x] Evaluate performance impact by switching to GraphWrap
- [x] Evaluate maintenance difference (currently hybrid of declarative & dynamic vs entirely dynamic with GraphWrap)
- [x] Determine any breaking schemas changes
- [x] Evaluate licensing, currentness, and stability of GraphWrap
- [ ] Can we add backwards compatibility to address breaking changes

**Comment by PaulGilmartin** [comment] 2021-12-15 20:08
Hi @jathanism 

I'm the maintainer/sole author of GraphWrap. I was pleased to see your interest in the library. I just wanted to add to what you remarked above.

First, I believe #[446](https://github.com/nautobot/nautobot/issues/446)would be solved with GraphWrap. I'm judging this off of the following comment in that thread: 
"_I worked on this for a while now, sadly none of the approaches that we could come up with proved viable. For posterity, let me document them:

The simplest way to make this work is to generate the schema everytime it is needed (i.e. on every API call). Unfortunately, this is prohibitively slow (on the order of seconds)."_

Generating the schema on API call is exactly what GraphWrap does. I have however never seen it take anything close to the order of a second to generate that schema though - the Python code it uses to do so is really quite light. I have had it running on a production API with possibly 50 distinct schemas and schema generation time is not noticeable. It is perhaps the case however that your API really is huge, I'm not sure.

For the other remaining open issue, I'm not quite familiar enough with your API to be able to comment on whether or not GraphWrap could handle it. 

If you do decide to investigate, I'd be more than willing to lend a hand with any issues or questions.

Cheers,

Paul

**Comment by jathanism** [comment] 2021-12-16 01:00
@PaulGilmartin Thank you for taking the time to comment here. I appreciate your interest in helping! This is definitely food for thought.

**Comment by glennmatthews** [comment] 2022-04-12 16:06
(Note that I also installed latest graph_wrap from git, as I encountered some other errors when using the latest release version, before even getting to the need for the above changes)

**Comment by PaulGilmartin** [comment] 2022-04-12 16:28
@glennmatthews thanks for looking into graphwrap. I'll try to address the points you raised in your first post:


- "List endpoint names would change from (devices, sites, etc.) to (all_devices, all_sites, etc.) - might be possible to enhance graph_wrap to make this configurable?" - I don't think making that configurable should be too difficult, so I'm happy to try out implementing that feature.
- "It looks like graph_wrap currently only supports integer PKs on its detail endpoints..." - It looks like graphene comes with a UUID type, so this should work for this use case. I feel like it should be possible for graph wrap to inspect at run time the type of the id/pk field, so supporting non-integer pks may be doable without too much work. I'd need to dig into that one before I can say for sure though.
- Could you tell me which errors you encountered from the latest pypi release which were not in the Github release? 

Cheers,

Paul

**Comment by PaulGilmartin** [comment] 2022-04-12 16:43
@glennmatthews For your second comment

> A few more observations:
> 
> graph_wrap seems to be very cautious about re-using types, resulting in a lot of apparent duplicate types in the generated schema, for example:
> 
> ```graphql
> type vlan_type {
>   id: String!
>   url: vlan_type!
>   vid: Int!
>   name: String!
>   display: GenericScalar!
> }
> 
> type vlan_type_2 {
>   id: String!
>   url: vlan_type!
>   vid: Int!
>   name: String!
>   display: GenericScalar!
> }
> 
> type vlan_type_3 {
>   id: String!
>   url: vlan_type!
>   vid: Int!
>   name: String!
>   display: GenericScalar!
> }
> ```
> 
> As can be seen above, the generated schema types are often lacking quite a few fields, notably many (but not all) of our `Nested*Serializer` fields appear to be absent, as well as various others - compare to our existing GraphQL VLANType:
> 
> ![image](https://user-images.githubusercontent.com/5603551/163007715-77249db6-f7a1-4ca8-8a7a-eb7a7f242469.png)
> 
> I will say though that generating the GraphQL schema from graph_wrap is _very_ fast - so it could still very much be worth investigating further whether it could be enhanced and fixed as needed to support all of our schema.

My lack of familiarity with your API makes this one a little tricker to say exactly what's going on. I'll try to justify the numbering of the types via an example which can be found in the graphwrap unit tests.

Suppose I have a serializer

```
class AuthorSerializer(serializers.ModelSerializer):
    user = UserSerializer()
    entries = serializers.ListSerializer(
         child=PostSerializer(source='entries'))
    amount_of_entries = serializers.SerializerMethodField()
    name = serializers.CharField(source='get_name')
    colours = serializers.ListField(
        child=serializers.CharField(), default=['blue', 'green'])

    class Meta:
        model = Author
        fields = [
            'name',
            'age',
            'active',
            'profile_picture',
            'user',
            'entries',
            'amount_of_entries',
            'colours',
        ]
```
This defines for me an `author_type`:

```
type author_type {
  name: String!
  age: Int
  active: Boolean!
  profile_picture: String
  user: user_type!
  entries: [post_type]!
  amount_of_entries: GenericScalar!
  colours: [String]!
}
```

Now suppose I have another "limited" serializer for the Author model,
```
class WrittenBySerializer(serializers.ModelSerializer):
    name = serializers.CharField(source='get_name')

    class Meta:
        model = Author
        fields = ['name']
```

and this is used in my PostSerializer

```
class PostSerializer(serializers.ModelSerializer):
    written_by = WrittenBySerializer(source='author')
    author = serializers.HyperlinkedRelatedField(
        view_name='author-detail',
        read_only=True
    )
```



graphwrap will build the schema for this second author type schema as follows:
```
type post_type {
  written_by: author_type_2!
  author: author_type!
```
where
```
type author_type_2 {
  name: String!
}
```

Could there be something similar happening in your API where the vlan model has several distinct serializers?

For the missing fields, that's very confusing. Could you link me to the vlan DRF API?

**Comment by glennmatthews** [comment] 2022-04-12 17:32
Thanks for the very quick responses! It may be a little while before I can circle back around to reply in detail, but:

- For most models we have a Serializer and a NestedSerializer (e.g. `VLANSerializer` and `NestedVLANSerializer`) - it hadn't occurred to me as a possibility, but the `NestedVLANSerializer`'s set of fields does correspond to the three `vlan_type` types being generated, so I think that's a great direction to investigate.
- A reasonably up-to-date set of API docs can be seen at https://demo.nautobot.com/api/docs/.

**Comment by PaulGilmartin** [comment] 2022-04-15 01:15
- "_List endpoint names would change from (devices, sites, etc.) to (all_devices, all_sites, etc.) - might be possible to enhance graph_wrap to make this configurable?_". I decided to go ahead and implement this option. You can read about how to change the list endpoint naming convention here: https://github.com/PaulGilmartin/graph_wrap#understanding-the-schema
- "It looks like graph_wrap currently only supports integer PKs on its detail endpoints..."  - I've also added support for non-integer id values. In my test setup, I gave my Author model a UUID field and the schema looks like this now:
```
type author_type {
  name: String!
  age: Int
  active: Boolean!
  profile_picture: String
  user: user_type!
  entries: [post_type]!
  amount_of_entries: GenericScalar!
  colours: [String]!
  id: UUID!
}
```

**Comment by glennmatthews** [comment] 2022-04-15 14:56
That's awesome, thank you so much! I'll give it a try with your latest version this afternoon.

**Comment by glennmatthews** [comment] 2022-04-15 18:41
@PaulGilmartin With the latest code, generating the schema throws the following exception:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/graph_wrap/django_rest_framework/__init__.py", line 6, in schema
    return SchemaFactory.create_from_api()
  File "/usr/local/lib/python3.7/site-packages/graph_wrap/django_rest_framework/schema_factory.py", line 25, in create_from_api
    return cls(views).create()
  File "/usr/local/lib/python3.7/site-packages/graph_wrap/django_rest_framework/schema_factory.py", line 72, in create
    schema = graphene.Schema(query=Query, types=non_root_types)
  File "/usr/local/lib/python3.7/site-packages/graphene/types/schema.py", line 78, in __init__
    self.build_typemap()
  File "/usr/local/lib/python3.7/site-packages/graphene/types/schema.py", line 168, in build_typemap
    initial_types, auto_camelcase=self.auto_camelcase, schema=self
  File "/usr/local/lib/python3.7/site-packages/graphene/types/typemap.py", line 80, in __init__
    super(TypeMap, self).__init__(types)
  File "/usr/local/lib/python3.7/site-packages/graphql/type/typemap.py", line 31, in __init__
    self.update(reduce(self.reducer, types, OrderedDict()))  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/graphene/types/typemap.py", line 88, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/local/lib/python3.7/site-packages/graphene/types/typemap.py", line 117, in graphene_reducer
    return GraphQLTypeMap.reducer(map, internal_type)
  File "/usr/local/lib/python3.7/site-packages/graphql/type/typemap.py", line 109, in reducer
    field_map = type_.fields
  File "/usr/local/lib/python3.7/site-packages/graphql/pyutils/cached_property.py", line 22, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.7/site-packages/graphql/type/definition.py", line 198, in fields
    return define_field_map(self, self._fields)
  File "/usr/local/lib/python3.7/site-packages/graphql/type/definition.py", line 212, in define_field_map
    field_map = field_map()
  File "/usr/local/lib/python3.7/site-packages/graphene/types/typemap.py", line 275, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/usr/local/lib/python3.7/site-packages/graphene/types/typemap.py", line 88, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/local/lib/python3.7/site-packages/graphene/types/typemap.py", line 117, in graphene_reducer
    return GraphQLTypeMap.reducer(map, internal_type)
  File "/usr/local/lib/python3.7/site-packages/graphql/type/typemap.py", line 109, in reducer
    field_map = type_.fields
  File "/usr/local/lib/python3.7/site-packages/graphql/pyutils/cached_property.py", line 22, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.7/site-packages/graphql/type/definition.py", line 198, in fields
    return define_field_map(self, self._fields)
  File "/usr/local/lib/python3.7/site-packages/graphql/type/definition.py", line 212, in define_field_map
    field_map = field_map()
  File "/usr/local/lib/python3.7/site-packages/graphene/types/typemap.py", line 275, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/usr/local/lib/python3.7/site-packages/graphene/types/typemap.py", line 88, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/local/lib/python3.7/site-packages/graphene/types/typemap.py", line 93, in graphene_reducer
    return self.reducer(map, type.of_type)
  File "/usr/local/lib/python3.7/site-packages/graphene/types/typemap.py", line 88, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/local/lib/python3.7/site-packages/graphene/types/typemap.py", line 93, in graphene_reducer
    return self.reducer(map, type.of_type)
  File "/usr/local/lib/python3.7/site-packages/graphene/types/structures.py", line 25, in of_type
    return get_type(self._of_type)
  File "/usr/local/lib/python3.7/site-packages/graphene/types/utils.py", line 45, in get_type
    return _type()
  File "/usr/local/lib/python3.7/site-packages/graph_wrap/django_rest_framework/api_transformer.py", line 213, in <lambda>
    return lambda: self.type_mapping[name]
KeyError: 'tag_type_2'
```

I don't see this error if I roll back graph_wrap to commit 7fff829dc7d2818c57de00d3055fc6c50fae7484, FWIW, so it seems to have been introduced by https://github.com/PaulGilmartin/graph_wrap/commit/be24ac63f1abba5d4961d0b479bb8c22e27ad923.

Thank you again! I'll keep investigating to see if I can help identify the cause of the error.

**Comment by PaulGilmartin** [comment] 2022-04-15 18:45
Ah damn. Thanks for raising, I'll try to identify the error too.

**Comment by PaulGilmartin** [comment] 2022-04-15 19:18
@glennmatthews could you try pulling the latest commit from master? I made a potential fix. I noticed I forgot to also pass around "seen_nested_serializers" into the transformers. Not completely sure if that will fix your issue but it was definitely a bug I introduced in https://github.com/PaulGilmartin/graph_wrap/commit/be24ac63f1abba5d4961d0b479bb8c22e27ad923

**Comment by glennmatthews** [comment] 2022-04-15 19:51
Same error still, unfortunately.

**Comment by PaulGilmartin** [comment] 2022-04-15 19:58
Ok, sorry about that! 
I have a potential reproduction of the error, so will keep digging into it.

**Comment by PaulGilmartin** [comment] 2022-04-15 20:16
@glennmatthews I amended my last commit. My fix in the last commit wasn't 100% finished I realised. When you get a chance please try pulling in master and trying again :).
Apologies for the back and forth, it's a little hard to diagnose when I don't have the same API in front of me to test on.

**Comment by glennmatthews** [comment] 2022-04-15 21:00
No need to apologize! You're going above and beyond here and I really appreciate it. No error seen with latest code 🎉 . Can also confirm that the customized list-endpoint names and UUID PKs look to be working as well, and I don't see any duplicate types now either (just two types for most models that have both a Serializer and NestedSerializer).

I do now see some models where there's only one type in the schema and it appears to be the brief/nested one only, but I'll leave that be until I can do some digging on Monday. 

Thanks again and have a great weekend!

**Comment by glennmatthews** [comment] 2022-04-29 20:54
Some more observations as to remaining issues and areas where graph_wrap's schema differs from our current constructed schema.

### Missing types for non-nested-serializers for some models

Several models only generated a `type` corresponding to their brief/NestedSerializer rather than the full Serializer class; I see at least the following models in this situation:

- Cable
- Cluster
- Device
- Interface
- ProviderNetwork
- RearPort
- RearPortTemplate
- SecretsGroup
- Site
- Tenant
- User
- VirtualMachine
- VLAN

Going by the order in which types are listed in the base `Query` object, my best working theory is that it's a discovery-order issue of some sort. The types are listed under `Query` in the same order they're listed in each app's `api/urls.py` file, for example, for the `circuits` app:

```python
# Providers
router.register("providers", views.ProviderViewSet)
    
# Circuits
router.register("circuit-types", views.CircuitTypeViewSet)
router.register("circuits", views.CircuitViewSet)
router.register("circuit-terminations", views.CircuitTerminationViewSet)
    
router.register("provider-networks", views.ProviderNetworkViewSet)
```

and the corresponding start of the GraphQL schema:

```graphql
type Query {
  provider(id: UUID!): provider_type
  providers(orm_filters: String): [provider_type]
  circuittype(id: UUID!): circuittype_type
  circuittypes(orm_filters: String): [circuittype_type]
  circuit(id: UUID!): circuit_type
  circuits(orm_filters: String): [circuit_type]
  circuittermination(id: UUID!): circuittermination_type
  circuitterminations(orm_filters: String): [circuittermination_type]
  providernetwork(id: UUID!): providernetwork_type
  providernetworks(orm_filters: String): [providernetwork_type]
...
```

The Provider viewset gets loaded first, resulting in a `provider_type` corresponding to `ProviderSerializer` correctly. Same for `CircuitType`, `Circuit`, `CircuitTermination` -- but `Circuit` has a `NestedTenantSerializer`, and `CircuitTermination` has a `NestedProviderNetworkSerializer`, and lo and behold, `Tenant` and `ProviderNetwork` get stuck with only their nested serializers as a GraphQL type, even though `ProviderNetwork`, discovered next, has a non-nested Serializer of its own that should be used here instead.


### Computed fields missing from the schema types

Not surprisingly, because our `computed_fields` field is not serialized by default, but is only included as an opt-in field when specifically requested as a query parameter (custom code on our part), `computed_fields` are not included in any of the generated GraphQL types. We'll have to figure out how to add this as an extension.

### URL fields are represented as an object type rather than a String

We have a general pattern where any given object's serializer includes a `url` field providing a direct link to that object, e.g. for RackSerializer, we have:

```python
url = serializers.HyperlinkedIdentityField(view_name="dcim-api:rack-detail")
```

graph_wrap is representing these `url` fields as self-referential types rather than as string fields, e.g.:

```graphql
type rack_type {
  id: UUID!
  url: rack_type!
```

This probably needs to be corrected, though it's not a critical issue for us as our current generated GraphQL schema (without graph_wrap) doesn't include the `url` field at all, so even if uncorrected this wouldn't be a breaking change or anything.

### Specific data types

Most of our models have a `created` DateField and a `last_updated` DateTimeField. In our current GraphQL schema these are represented as `Date` and `DateTime` types, while the graph-wrap schema represents them simply as `String` types. I'm not sure what the impact of keeping them as String would be, but I think more specificity is probably desirable.

Similarly, fields that have a constrained set of choices are represented in our current GraphQL schema by a custom enum type for each choice-set, while in graph-wrap's generated schema they're just `GenericScalar` fields.

### Handling of Status fields

For historical reasons, our REST API serializes FKs to the `Status` class as JSON objects of the form `{"name": "active", "label": "Active"}` rather than as proper foreign-keys or nested serializer objects like most other FK fields. graph-wrap is interpreting these fields as `String` fields rather than using a dedicated type for them. We'd need to figure out how to fix this in order to avoid a breaking change here.

### Query filters

graph_wrap provides an `orm_filters: String` parameter that can contain any django-filters arguments (`devices(orm_filters: "name=rtr1")` whereas our current GraphQL schema has each available filter as a separate parameter (`devices(name: "rtr1")`). This would be a breaking change for us.

Open question: does graph_wrap's schema support filtering at levels below the Query root? E.g. `{ racks { devices (orm_filters: "name=rtr1") { name } }`? Or only one level of filtering?


### Additional fields

For example, our custom CircuitTerminationType includes `cable_peer_interface`, `cable_peer_frontport`, `connected_interface`, etc. that are not presently part of the REST API and so are not represented in the graph-wrap generated GraphQL schema.

It may be that our best solution here is simply to add these fields to the REST API, rather than trying to augment the generated schema, but I wanted to include this here for completeness

## Conclusion

I do still very much think that graph-wrap could be a viable library for us to adopt here. We'd need to chase down the above issues (and possibly contribute code upstream if needed) but the generated schema is, all in all, pretty close already to what we already have, and it would be great to be able to rip out our bespoke schema code.

**Comment by PaulGilmartin** [comment] 2022-05-01 14:29
@glennmatthews Thanks for the great analysis. For the first issue you mentioned about the types being incorrect: I have just pushed what I believe to be a fix for this. I was able to recreate a similar issue simply by reordering the registration of viewsets in my test suite, so I think you were bang on the money with your assumptions.

For the other points you raised, I can try to address the ones I understand/I can contribute to as soon as I get some time. I'd appreciate if you could let me know whether or not I fixed the first issue :)

**Comment by PaulGilmartin** [comment] 2022-05-01 15:27
**URL fields are represented as an object type rather than a String**

For this one, the fact that a HyperLinkedIdentity and HyperLinkedRelated point to the full object types of the related type is by design. This allows a user a graphql user to extract nested values if they choose to whilst also maintaining that only a URL/id is exposed to a REST user. In my view, this allows graph wrap to solve the n+1 problem  for a DRF API. I wrote a little more about this here: https://paul-gilmartin89.medium.com/django-when-rest-may-not-be-enough-and-how-a-graphql-layer-can-help-save-you-d9bc58919d1

You can let me know if you think this is in any way problematic, but currently I am of the belief that it makes sense for a graphql schema.

**Comment by glennmatthews** [comment] 2022-05-02 13:09
Can confirm that the schema types appear correct after updating to PaulGilmartin/graph_wrap@7dabba53ba5c4de2900b3feaf398aa88a76f7e16 - thank you again!

**Comment by PaulGilmartin** [comment] 2022-05-02 13:49
Some more remarks on the above:


- **Specific data types**: the date/datetime issue is easy to fix. For the custom scalars, I guess we need to add some code which allows a user to extend the `base_types` dict in `get_transformer` with a scalar and transformer of their choice. This should be relatively straightforward I think.

- **Query filters**: Fixing this in a backwards compatible way will be harder than the other issues. I'll try to see what I can come up with. To the point about nested filtering - I just tried it out and it looks like graph-wrap doesn't currently support that. I'll also try to find out how much work is involved in adding support for that.

**Comment by bryanculver** [comment] 2022-05-03 16:13
Continuing with to #1738

**Closed by bryanculver** 2022-05-03 16:13 UTC
Labels: type: housekeeping
