### ISSUE TITLE
App provided table column extensions

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#4899] opened 2023-12-01 17:10 UTC
### As ...

P.D. - Plugin Developer

### I want ...

The ability to contribute extra columns to existing tables in core.

### So that ...

I can add additional data/context to a core table that is relevant to my app.

### I know this is done when...

I have a similar app API interface to filter extensions that allows me to register new columns to existing tables.

I expect to specify my columns as django_tables2/nautobot core Column classes.

Because columns are typically tightly coupled to data on the instance, it would be a good idea to provide a mechanism that allows me to optionally override/augment the queryset being used by the table. This way I could add a prefetch for my app's related model, etc.

### Optional - Feature groups this request pertains to.

- Plugins (and other Extensibility)

**Comment by glennmatthews** [comment] 2023-12-01 21:10
Duplicate of #2147?

**Closed** 2024-10-25 22:25 UTC
Labels: type: feature
