### ISSUE TITLE
Add a management command to manually prune ObjectChange (Change Log) objects

### ISSUE THREAD

**Issue by joewesch** [nautobot/nautobot#2501] opened 2022-09-27 14:14 UTC
### As ...

Patti - Platform Admin

### I want ...

To be able to manually prune ObjectChange objects based on the [CHANGELOG_RETENTION](https://nautobot.readthedocs.io/en/stable/configuration/optional-settings/?h=changelog_retention#changelog_retention) setting.

### So that ...

I have the ability to prune objects in my database intentionally rather than wait for them to be [cleaned up randomly](https://github.com/nautobot/nautobot/blob/c50d3e90d7754991f4981fb16090212bc88d0900/nautobot/extras/signals.py#L99-L103) upon creation of a new object.

### I know this is done when...

I can run a management command and all ObjectChange older than the number of days in my retention setting are removed.

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [X] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [X] Other (not directly a platform feature)

### Database Changes

None

### External Dependencies

None

**Comment by jdrew82** [comment] 2023-08-09 21:56
Large changelog retention tables in the database can trigger a worker to be killed by the "randomized" cleanup process in the signal [here[(https://github.com/nautobot/nautobot/blob/22c0fe3876dc714bc79fe6925ea204a6a466c356/nautobot/extras/signals.py#L122). This appears to be caused by the large amount of memory being consumed when trying to cleanup the changelogs. This was seen with a changelog table approximately 65GB in size. The same result has been seen trying to cleanup changelogs manually via the ORM.

**Comment by glennmatthews** [comment] 2024-03-19 13:42
This will be addressed by implementing a system Job for changelog cleanup as a part of #3749; this Job will be runnable via the `nautobot-server runjob` management command so no new management command should be necessary.

**Comment by glennmatthews** [comment] 2024-04-10 15:18
`LogsCleanup` job added for 2.3 by #5442.

**Closed by glennmatthews** 2024-04-10 15:18 UTC
Labels: type: feature
