### ISSUE TITLE
DynamicGroup Unable To Filter On Region, Location

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot#2513] opened 2022-09-28 14:27 UTC
### Environment
* Nautobot version (Docker tag too if applicable): v1.4.X
* Python version: 3.8
* Database platform, version: PG 13 & 14
* Middleware(s):

### Steps to Reproduce
1. Create set of devices in a site that is nested in a Region
2. Create DynamicGroup with dcim.Device content-type and only filter being the created Region

Replicable in demo.nautobot.com

### Expected Behavior
Ability use DynamicGroups to filter based on most child Region AND any level of parent Region

### Observed Behavior
When Region filter is applied DynamicGroup.members returns zero Device objects.

**Comment by bryanculver** [comment] 2022-09-28 14:47
Confirmed this also is an issue for Locations as well.

I suspect this is an issue with the logic for handling `TreeNodeMultipleChoiceFilter`. It's resulting in a `__in` lookup expression but `TreeNodeMultipleChoiceFilter` has an overloaded `filter` method which isn't being evaluated for Dynamic Groups.

**Comment by jathanism** [comment] 2022-10-18 16:08
Related to #2487

**Comment by jathanism** [comment] 2022-10-20 18:11
The bug is here in `NaturalKeyOrPKMultipleChoiceFilter.get_filter_predicate()`:

```python
        # If it's not a pk and not a list/qs generate then it's a slug and the filter predicate
        # needs to be nested (e.g. `{"site__slug": "ams01"}`) so that it can be useable in `Q`
        # objects.
        #
        # FIXME(jathan): It feels weird to have a list/qs make its way to `get_filter_predicate()`
        # which if you inspect the source for `django_filters.MultipleChoiceFilter.filter()` should
        # be handling those to generate singular filter predicates and concatentating them.
        if not is_pk and not isinstance(v, (list, models.QuerySet)):  # <-- HERE
            name = f"{self.field_name}__{self.field.to_field_name}"
        # Otherwise just trust the field_name
        else:
            logger.debug("UUID or list/qs detected: Filtering using field name")
            name = self.field_name
```

If we set Region to "Netherlands", it SHOULD result in a filter predicate of:

```
{'site__region__slug__in': ['netherlands']}

```

But instead it is resolving to:

```
{'site__region__in': ['netherlands']}
```

Causing the filter to return an empty queryset.

**Comment by jathanism** [comment] 2022-10-21 18:05
> Confirmed this also is an issue for Locations as well.
> 
> I suspect this is an issue with the logic for handling `TreeNodeMultipleChoiceFilter`. It's resulting in a `__in` lookup expression but `TreeNodeMultipleChoiceFilter` has an overloaded `filter` method which isn't being evaluated for Dynamic Groups.

You were spot on with this initial assessment, except the assertion wasn't quite right. The root issue here is that `in` lookup expression for filters is not correct here, as a multiple-choice filters just behave like a list of `exact` lookups. The `in` expression is used for CSV_based arguments a la `?foo=bar,baz,spam` and not multi-value inputs like `?foo=bar&foo=baz&foo=spam`. 

The other issue that was exposed once the lookup expression handling was fixed, is how we are collating the nested tree results and how our `Q` object generation. Dynamic Groups are not currently considering tree-based filters, and they should. However, instead of making this directly a problem for groups, it we will need to adapt the Q-based-filter generation to include nested members in some way.

**Comment by jathanism** [comment] 2022-10-21 19:04
> The bug is here in `NaturalKeyOrPKMultipleChoiceFilter.get_filter_predicate()`:
> 
> ```python
>         # If it's not a pk and not a list/qs generate then it's a slug and the filter predicate
>         # needs to be nested (e.g. `{"site__slug": "ams01"}`) so that it can be useable in `Q`
>         # objects.
>         #
>         # FIXME(jathan): It feels weird to have a list/qs make its way to `get_filter_predicate()`
>         # which if you inspect the source for `django_filters.MultipleChoiceFilter.filter()` should
>         # be handling those to generate singular filter predicates and concatentating them.
>         if not is_pk and not isinstance(v, (list, models.QuerySet)):  # <-- HERE
>             name = f"{self.field_name}__{self.field.to_field_name}"
>         # Otherwise just trust the field_name
>         else:
>             logger.debug("UUID or list/qs detected: Filtering using field name")
>             name = self.field_name
> ```
> 
> If we set Region to "Netherlands", it SHOULD result in a filter predicate of:
> 
> ```
> {'site__region__slug__in': ['netherlands']}
> ```
> 
> But instead it is resolving to:
> 
> ```
> {'site__region__in': ['netherlands']}
> ```
> 
> Causing the filter to return an empty queryset.

Just correcting myself here. What we in fact want is that the filter predicate be: 

```
 {'site__region__slug': 'netherlands'}
```

`MultipleChoiceFilter`s and subclasses generate a filter predicate for each value in the list of values for the filter argument. So as I had stated above, this means that it handles it like a list of `exact` filter lookups and not a membership `in` test on a list of values.

If `conjoined=False` is set on the filter (the default), these individual `exact` filters are joined with OR, otherwise when `conjoined=True` they are joined with `AND`.

**Comment by whitej6** [comment] 2022-10-23 22:04
What about nested regions?

**Closed** 2022-10-24 16:52 UTC
Labels: type: bug

**Comment by jathanism** [comment] 2022-10-27 19:52
> What about nested regions?

![image](https://user-images.githubusercontent.com/138052/198385216-a7aac816-84aa-406e-8d50-bd84f48049da.png)

Yep since they are also using `TreeNodeMultipleChoiceFilter`. 😎

**Comment by jathanism** [comment] 2022-10-27 19:52
However, @whitej6, see also: #2693
