### ISSUE TITLE
GraphQL : _custom_field_data should be a GenericScalar instead of a JSONString

### ISSUE THREAD

**Issue by dgarros** [nautobot/nautobot#567] opened 2021-06-13 21:14 UTC
### Environment
* Python version: 3.7
* Nautobot version: 1.0.2

### Steps to Reproduce
1. Connect to the GraphiQL interface
2. Inspect the schema for DeviceType
3. Confirm that `_custom_field_data: JSONString!` is present instead of `_custom_field_data: GenericScalar` 

### Observed Behavior
_custom_field_data on all model is defined as a JSONString in the schema and as a result it will be passed as a string in the response instead of being converted to a JSON object.

<img width="503" alt="Screen Shot 2021-06-13 at 5 07 10 PM" src="https://user-images.githubusercontent.com/304126/121821875-d0b3aa80-cc69-11eb-8bd9-066c14d75276.png">

<img width="556" alt="Screen Shot 2021-06-13 at 5 08 44 PM" src="https://user-images.githubusercontent.com/304126/121821909-05bffd00-cc6a-11eb-98c8-1dc355ff4e35.png">

### Expected Behavior
I would expect all JSONField to be converted to `GenericScalar` in GraphQL to be represented as JSON object in GraphQL instead of being returned as string. The conversion is working properly for other JSONField like `local_context_data`

I'm almost sure it was working before `custom_field_data` got renamed to `_custom_field_data`. As far as I remember the  conversion from JSONString to GenericScalar is currently done globally in [nautobot/core/graphql/__init__.py](https://github.com/nautobot/nautobot/blob/develop/nautobot/core/graphql/__init__.py#L10)

**Comment by jathanism** [comment] 2021-06-15 21:21
Great catch. Thanks for submitting this.

**Comment by carbonarok** [comment] 2021-07-01 15:05
Unable to reproduce this issue. If this issue comes back please feel free to re-open this bug.

**Comment by dgarros** [comment] 2021-09-28 22:50
Not sure if this is a regression or if it was never fixed but the same issue is present in the sandbox running 1.1.3 right now
https://demo.nautobot.com/graphql/

**Comment by glennmatthews** [comment] 2021-09-29 18:06
My suspicion is that this is an initialization-order issue of some sort, as we've had a very difficult time reproducing this issue consistently.

**Comment by nniehoff** [comment] 2021-11-01 14:45
@glennmatthews I think you are correct, as this is reproduced on https://demo.nautobot.com can you please re-open this issue.  https://test.nautobot.com does not reproduce this.  Hopefully, this helps narrow it down.

**Comment by glennmatthews** [comment] 2021-11-01 19:34
Still haven't been able to successfully reproduce this locally. One interesting/odd detail (as Damien stated in the initial issue description) is that it appears that *only* `_custom_field_data` is being mis-represented as a JSONString; other JSONFields in the Nautobot data model (even on demo.nautobot.com) are correctly represented as GenericScalars.

**Comment by nniehoff** [comment] 2021-11-01 21:32
@glennmatthews in the environments affected I can easily resolve the issue by removing the circuit maintenance plugin.  However, I can not reproduce the problem yet by installing the circuit maintenance plugin in a fresh environment.

**Comment by nniehoff** [comment] 2021-11-01 22:17
It looks like this is an issue with circuit maintenance "0.2.5" I believe this may be fixed in 0.3.

**Comment by glennmatthews** [comment] 2021-11-02 12:29
I can verify that the issue is being seen in at least one environment that is currently running circuit-maintenance 0.3.2, so that may not be fully fixed. Thanks for the pointer though, I'll do some digging into the plugins and see if I can get anywhere.

**Comment by glennmatthews** [comment] 2021-11-02 13:15
Looks like the trigger is installing and activating *any plugin* that provides a `graphql.types` module with custom types. As you noticed, `nautobot-circuit-maintenance` 0.2.x has such a module but 0.3.x does not. In the environment with 0.3.2 where the issue is still seen, there is a different plugin installed that also has its own `graphql.types` module, hence why the issue is still present. Thank you for the clues @nniehoff!

**Closed** 2021-11-05 17:38 UTC
Labels: type: bug, status: accepted
