### ISSUE TITLE
MySQL cannot retrieve config context data

### ISSUE THREAD

**Issue by carbonarok** [nautobot/nautobot#435] opened 2021-05-12 14:55 UTC
### Environment
* Python version: 3.7
* Nautobot version: 1.0.1

### Steps to Reproduce
1. Start nautobot with MySQL database
2. Add device with a local config context
3. View device config context tab

### Expected Behavior
Display config context correctly.

### Observed Behavior
```
Traceback (most recent call last):
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/nautobot/utilities/views.py", line 94, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/nautobot/core/views/generic.py", line 81, in get
    instance = get_object_or_404(self.queryset, **kwargs)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/django/shortcuts.py", line 76, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/cacheops/query.py", line 353, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/cacheops/query.py", line 283, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/cacheops/transaction.py", line 93, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-as-code--7dpvOAb-py3.7/lib/python3.7/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY V0.`weight`, V0.`name`) AS `_data` FROM `extras_configcontext` V0 LEFT ' at line 1")
```

**Comment by jathanism** [comment] 2021-05-12 15:55
Uh oh. I am really surprised this wasn't caught by our testing. Can you please clarify what version of MySQL you're using and what the local config context is that you created so that we can try to reproduce this?

**Comment by carbonarok** [comment] 2021-05-12 16:36
`mysql  Ver 8.0.23`

I was using dummy values for the config contexr `{"test":"test_value}`

**Comment by jathanism** [comment] 2021-05-12 20:10
Hmm, I'm not able to reproduce this w/ a single device, MySQL 8.0.23 and local config context of `{"test": "test_value"}`.  We have to go deeper.

**Comment by jathanism** [comment] 2021-06-09 19:25
Still unable to reproduce this on Nautobot v1.0.3b1. Closing.

**Closed by jathanism** 2021-06-09 19:25 UTC
Labels: status: accepted, status: current, type: bug
